### ISSUE TITLE
npm install with dependency issue.

### ISSUE THREAD

**Issue by 987603843** [auroral-ui/hexo-theme-aurora#10]
请问npm install 的时候总是报那个包的错误 好像版本不适配的问题 该怎么解决呢

**Comment by TriDiamond** [comment]
@987603843 能否提供具体报了什么错误吗？把报错信息或者截图提供一下哈。

**Comment by 987603843** [comment]
你好 是这个报错信息



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Benny ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [auroral-ui/hexo-theme-aurora] npm install (#10)





 
@987603843 能否提供具体报了什么错误吗？把报错信息或者截图提供一下哈。

**Comment by 987603843** [comment]
![image](https://user-images.githubusercontent.com/49261839/113127665-98e0bd80-924b-11eb-8764-1ac9a5381edb.png)

**Comment by TriDiamond** [comment]
@987603843 先检查一下你的 NPM 版本，看是不是在版本7+， 如果是的话，也有一些同学用 NPM 7 安装不了依赖。我推荐你安装一下 [YARN](https://yarn.bootcss.com/docs/install) 然后使用 yarn 安装就没有问题了。

**Comment by 987603843** [comment]
好的 谢谢



发自我的iPhone


------------------ Original ------------------
From: Benny Guo ***@***.***&gt;
Date: Wed,Mar 31,2021 6:19 PM
To: auroral-ui/hexo-theme-aurora ***@***.***&gt;
Cc: 987603843 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [auroral-ui/hexo-theme-aurora] npm install (#10)





 
@987603843 先检查一下你的 NPM 版本，看是不是在版本7+， 如果是的话，也有一些同学用 NPM 7 安装不了依赖。我推荐你安装一下 YARN 然后使用 yarn 安装就没有问题了。

**Comment by TriDiamond** [comment]
> 好的 谢谢 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Benny Guo ***@***.***&gt; Date: Wed,Mar 31,2021 6:19 PM To: auroral-ui/hexo-theme-aurora ***@***.***&gt; Cc: 987603843 ***@***.***&gt;, Mention ***@***.***&gt; Subject: Re: [auroral-ui/hexo-theme-aurora] npm install (#10) @987603843 先检查一下你的 NPM 版本，看是不是在版本7+， 如果是的话，也有一些同学用 NPM 7 安装不了依赖。我推荐你安装一下 YARN 然后使用 yarn 安装就没有问题了。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

如果您成功了麻烦告知我一声哈，我会修改一下主题的文档提醒一下新使用者使用 Yarn 安装依赖。谢谢你的提问～

**Comment by TriDiamond** [comment]
# todo
记录以下问题，需要在文档中补充

1. 使用 NPM 7 以上去安装主题依赖会出现以来包安装错误
2. 需要使用 NPM 6 才能正常安装
3. 或者推荐使用 Yarn 进行包安装

**Comment by TriDiamond** [comment]
这个问题主题版本 1.1.0 + 已经解决。
