### ISSUE TITLE
代码高亮似乎有一些问题

### ISSUE THREAD

**Issue by wakkana** [auroral-ui/hexo-theme-aurora#100]
![4EB8AF6B-632A-48C0-9164-77F100AF6498](https://user-images.githubusercontent.com/72391178/118376511-ea29ee00-b5fa-11eb-8e1c-78f25dfa648c.png)
在黑色背景下过于刺眼 而在作者的文章中是黑色背景
记得刚设置时记得是黑色的。应该是哪里改了也没注意···
尝试过 
更改主题颜色
更改暗黑模式/自动

从prismjs换回highlight 则背景变黑了 但又没有高亮···
是哪里设置有问题么

**Comment by Wakkana** [comment]
deploy后没有问题 可能是本地问题
