### ISSUE TITLE
[Aurora Generator Error] Mismatch post count after feature processing!

### ISSUE THREAD

**Issue by EdisonKnew** [auroral-ui/hexo-theme-aurora#104]

**Comment by RivenNero** [comment]
I also encountered this problem. I use node 16.3.0.

**Comment by TriDiamond** [comment]
@EdisonKnew @RivenNero Can one of you show me what posts you have in your source folder?

**Comment by RivenNero** [comment]
> @EdisonKnew @RivenNero Can one of you show me what posts you have in your source folder?

OK. This is my source folder structure:

```text
+---about
|       index.md
|
\---_posts
        hello-world.md
```

This is about/index.md:

```text
---
title: about
date: 2021-06-11 21:06:43
---

```

This is _posts/hello-world.md:

<pre>
---
title: Hello World
---
Welcome to [Hexo](https://hexo.io/)! This is your very first post. Check [documentation](https://hexo.io/docs/) for more info. If you get any problems when using Hexo, you can find the answer in [troubleshooting](https://hexo.io/docs/troubleshooting.html) or you can ask me on [GitHub](https://github.com/hexojs/hexo/issues).

## Quick Start

### Create a new post

``` bash
$ hexo new "My New Post"
```

More info: [Writing](https://hexo.io/docs/writing.html)

### Run server

``` bash
$ hexo server
```

More info: [Server](https://hexo.io/docs/server.html)

### Generate static files

``` bash
$ hexo generate
```

More info: [Generating](https://hexo.io/docs/generating.html)

### Deploy to remote sites

``` bash
$ hexo deploy
```

More info: [Deployment](https://hexo.io/docs/one-command-deployment.html)

</pre>

To be honest, this is a new site.

**Comment by TriDiamond** [comment]
I see, so this happens when having less than 3 posts. I will test it out.

**Comment by RivenNero** [comment]
> I see, so this happens when having less than 3 posts. I will test it out.

Maybe, because I was first use this theme. To be honest, it's a very nice theme!!

And I think this is the same as the other bug. #105
