### ISSUE TITLE
`快速上手`改进建议

### ISSUE THREAD

**Issue by guowei-gong** [auroral-ui/hexo-theme-aurora#106]
- https://aurora.tridiamond.tech/zh/guide/getting-started.html#%E6%AD%A5%E9%AA%A4-5-%E5%88%9B%E5%BB%BA-%E5%85%B3%E4%BA%8E-about-%E9%A1%B5%E9%9D%A2
  目前需要执行的应该是
  `hexo new page about`

- 在快速上手中未提示修改 hexo 默认配置中的 theme: aurora
![截屏2021-05-25 上午11 09 06](https://user-images.githubusercontent.com/62499904/119433848-a301d280-bd49-11eb-966b-6fec5c6fa33e.png)

**Comment by bennyxguo** [comment]
已经添加了
