### ISSUE TITLE
评论区匿名用户的头像不能正常显示

### ISSUE THREAD

**Issue by JaydenChang** [auroral-ui/hexo-theme-aurora#107]
![tt](https://user-images.githubusercontent.com/72348653/120088966-a1108880-c128-11eb-91b0-719cff50c025.png)
如图，在天朝ip下不能连接到gravatar这个网址，图片也加载不出来

**Comment by TriDiamond** [comment]
@JaydenChang 可以发一下你的博客链接给我看看吗？

**Comment by RivenNero** [comment]
> ![tt](https://user-images.githubusercontent.com/72348653/120088966-a1108880-c128-11eb-91b0-719cff50c025.png)
> 如图，在天朝ip下不能连接到gravatar这个网址，图片也加载不出来

国内部分地区对 Gravatar 的连接性确实不是很好。如果可以的话建议替换成国内的 Gravatar Mirror。

**Comment by JaydenChang** [comment]
> @JaydenChang 可以发一下你的博客链接给我看看吗？

https://jaydenchang.gitee.io

**Comment by JaydenChang** [comment]
@TriDiamond https://jaydenchang.gitee.io

**Comment by JaydenChang** [comment]
@RivenNero 那请问在哪里设置呢，那个config的yml没看到有

**Comment by JaydenChang** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/72348653/126884268-a2227c83-f7a0-4e1f-a4aa-f0f18f76f9a6.png)
如图，请问如何把gravatar那个图片源换成国内的呢，要正常加载图片要梯子，`node_modules`下的``hexo-theme-aurora`文件夹里面的配置文件也看过了，也找不到设置的地方
