### ISSUE TITLE
请问 i18n是怎么设置的=.=

### ISSUE THREAD

**Issue by Wakkana** [auroral-ui/hexo-theme-aurora#11]
en,cn 两个json加进去没有转换 是 menu.mydownloads
<img width="292" alt="截屏2021-03-31 下午7 08 35" src="https://user-images.githubusercontent.com/72391178/113135453-ba927280-9254-11eb-8ef0-229ba81ab127.png">
<img width="334" alt="截屏2021-03-31 下午7 08 09" src="https://user-images.githubusercontent.com/72391178/113135424-b36b6480-9254-11eb-96b1-c9900cf2085e.png">
<img width="446" alt="截屏2021-03-31 下午7 09 05" src="https://user-images.githubusercontent.com/72391178/113135523-cda54280-9254-11eb-970c-47730f76907b.png">

**Comment by TriDiamond** [comment]
这个记录一个问题：

> 因为是 vue SPA， 所以修改了这些代码方面的东西是需要重新打包的。我记录一下，后面文档里面会补充这个说明。

**需要在使用文档中补充以下说明：**
文档中注明，修改了语言的话是需要重新打包的。
- 进入 `themes/aurora` 然后执行 `yarn install & yarn build`
- 打包完之后，回到 hexo 根目录：`cd ../.. `
- 然后重新执行 `hexo cl & hexo g` 即可

**Comment by TriDiamond** [comment]
No need to repack theme since version 1.1.0, problem will not exist anymore.
