### ISSUE TITLE
 err: Error: Cannot find module 'truncate-html' &  err: TypeError: Cannot read property 'language' of undefined and more

### ISSUE THREAD

**Issue by NirajShr3stha** [auroral-ui/hexo-theme-aurora#114]
After running hexo server i am getting this error :

ERROR {
 Script load failed: %s themes\hexo-theme-aurora\scripts\index.js
 Script load failed: %s themes\hexo-theme-aurora\scripts\lib\generators\index.js
Script load failed: %s themes\hexo-theme-aurora\scripts\lib\generators\category.js
 Script load failed: %s themes\hexo-theme-aurora\scripts\lib\generators\page.js
Script load failed: %s themes\hexo-theme-aurora\scripts\lib\generators\post.js
 Script load failed: %s themes\hexo-theme-aurora\scripts\lib\generators\search.js
Script load failed: %s themes\hexo-theme-aurora\scripts\lib\generators\tag.js
 Script load failed: %s themes\hexo-theme-aurora\scripts\lib\helpers\mapper.js
Script load failed: %s themes\hexo-theme-aurora\scripts\lib\helpers\truncate-html.js

**Comment by makinbacon21** [comment]
I think I fixed this by running `npm update`
Don't run `npm audit fix --force` as I think this is what broke it

**Comment by nirajxhrestha** [comment]
thanks for the reply i will try it

**Comment by moonlightleaf** [comment]
it works

**Comment by moonlightleaf** [comment]
这是来自QQ邮箱的自动回复邮件。已收到您的邮件，我会尽快给您回复。祝您一切安好。
