### ISSUE TITLE
Busuanzi statistic plugin cannot be disabled?

### ISSUE THREAD

**Issue by wjpvandenheuvel** [auroral-ui/hexo-theme-aurora#115]
Value in yml:
enable: false

Yet, statistics are shown, bottom website. (after running hexo clean first)

![image](https://user-images.githubusercontent.com/416365/122520457-e8958080-d013-11eb-8fb4-3402a7352d11.png)

**Comment by TriDiamond** [comment]
I will check on this one, thanks for reporting.
