### ISSUE TITLE
Valine comments engine fails to load

### ISSUE THREAD

**Issue by makinbacon21** [auroral-ui/hexo-theme-aurora#116]
From browser console:
```
chunk-libs.9b3ced64.js:48 ReferenceError: Valine is not defined
    at o (post.bbd5d2f0.js:1)
    at post.bbd5d2f0.js:1
    at Ne (chunk-libs.9b3ced64.js:48)
    at Me (chunk-libs.9b3ced64.js:48)
    at Array.Ht.t.__weh.t.__weh (chunk-libs.9b3ced64.js:48)
    at st (chunk-libs.9b3ced64.js:48)
    at lt (chunk-libs.9b3ced64.js:48)
```
App ID and Key are valid, and I ran `npm install -s valine`
Comments section fails to load aside from heading
![image](https://user-images.githubusercontent.com/19865598/122857669-d6069a00-d2e6-11eb-9f21-c6cba9228b39.png)

**Comment by TriDiamond** [comment]
Valine core files are injected when building with Hexo. No need to `npm install the package`. Check your config file, see if you have enabled Valine.

**Comment by makinbacon21** [comment]
@TriDiamond pretty sure I have--repo link is [here](https://github.com/makinbacon21/thomasmak.in-blog) if you want to check

**Comment by TriDiamond** [comment]
> @TriDiamond pretty sure I have--repo link is [here](https://github.com/makinbacon21/thomasmak.in-blog) if you want to check

![image](https://user-images.githubusercontent.com/24708758/123353702-b1cfe500-d594-11eb-9b18-70f469ac2a4b.png)

You should upgrade to the latest version of the theme. Run: `npm update hexo-theme-aurora`

**Comment by makinbacon21** [comment]
@TriDiamond updating with npm did not change the minimum dependency version--I manually changed the value to 1.5.5^ and ran it again, and while it definitely did grab 1.5.5 (i think it did before too) the same issue is happening.

**Comment by TriDiamond** [comment]
Show me your `_config.aurora.yml` at root directiory.

**Comment by makinbacon21** [comment]
@TriDiamond 
![image](https://user-images.githubusercontent.com/19865598/123498660-5d158400-d5ff-11eb-98f4-5786f98684a7.png)
https://github.com/makinbacon21/thomasmak.in-blog/blob/master/_config.aurora.yml

**Comment by bennyxguo** [comment]
Should be fixed in the latest version. Thanks!
