### ISSUE TITLE
Disable RecentComments not working.

### ISSUE THREAD

**Issue by wjpvandenheuvel** [auroral-ui/hexo-theme-aurora#122]
I was wondering how to disable this widget. When starting a new blog and (obviously) nobody has commented yet, the recent comments widget remains empty and tries to load comments that are not there. I disabled recentcomments in the configfile in the gitalk section. 

Also, the amount of comments (66 in this case) still seems to correspond with the amount of comments on your own website. https://tridiamond.tech/

![image](https://user-images.githubusercontent.com/416365/118966607-21393000-b96a-11eb-8fe6-018f605fa7a2.png)

**Comment by TriDiamond** [comment]
Got it, I will look into this one.

**Comment by LoneDev6** [comment]
Still an issue, I hope you can fix it! :D
Thanks
