### ISSUE TITLE
err: TypeError: Cannot read property 'language' of undefined

### ISSUE THREAD

**Issue by ThinkBIM** [auroral-ui/hexo-theme-aurora#123]
hexo clean  err
![image](https://user-images.githubusercontent.com/29471873/125895427-987b3fa1-e996-4b70-912e-944dd15bcc04.png)

**Comment by dyingChinese** [comment]
when is the err found,i also discover

**Comment by littleboyfury** [comment]
you should run `yarn build` or `npm run build` in `themes/hexo-theme-aurora`

**Comment by W01fh4cker** [comment]
> you should run `yarn build` or `npm run build` in `themes/hexo-theme-aurora`

还是无法解决，依然报了这个错，很难受

**Comment by bennyxguo** [comment]
Fixed in the latest version!
