### ISSUE TITLE
Hyperlink Text Overflow

### ISSUE THREAD

**Issue by KernelErr** [auroral-ui/hexo-theme-aurora#124]
在手机上查看博客文章的时候，过长的超链接会溢出，导致网页宽度超过屏幕宽度，大佬有空能修修么
示例链接：[红米AC2100路由器刷Openwrt](https://www.lirui.tech/post/%E7%BA%A2%E7%B1%B3AC2100%E8%B7%AF%E7%94%B1%E5%99%A8%E5%88%B7Openwrt)

**Comment by TriDiamond** [comment]
看到了，谢谢你的 issue

**Comment by bennyxguo** [comment]
Fixed #253
