### ISSUE TITLE
Add feature to change cover image

### ISSUE THREAD

**Issue by a0981456759** [auroral-ui/hexo-theme-aurora#125]
請問要如何更改主要配色以及 cover image 呢

**Comment by panda850819** [comment]
cover image 如果是文章內部的話
在 buffer 那邊加上 cover 可以直接取代掉

主要配色他們是用三色漸層，可以在 _config.aurora.yml 上把 color 換了

**Comment by TriDiamond** [comment]
目前默认 Cover 没有配置更改，后面会提供的。谢谢你的反馈～

**Comment by SlahserZ** [comment]
> 目前默认 Cover 没有配置更改，后面会提供的。谢谢你的反馈～

hello, Does it has cover-image configuration now?

thanks.

**Comment by bennyxguo** [comment]
Since it's Vue SPA, default cover page can be changed if you clone your theme into the themes folder.
