### ISSUE TITLE
police_beian配置无效 会和beian配置的显示一样

### ISSUE THREAD

**Issue by coolkit-carl** [auroral-ui/hexo-theme-aurora#128]
我分别配置了beian和police_beian，运行：hexo clean & hexo g & hexo server 后，发现网站底部的：公安备案信息 和备案信息标题链接一样。

配置信息：
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-aurora": "^1.5.5",
    "hexo-theme-landscape": "^0.0.3"
  }
}

**Comment by Cassieqian** [comment]
@bennyxguo 
the question is still exit,could you tell me the data source?

**Comment by MeerOst** [comment]
臣附议

**Comment by kyeo-hub** [comment]
我也是这个问题，先没有看issue，自行找到解决途径。可以看看 #180 我写了解决办法。

**Comment by bennyxguo** [comment]
这个已经修复了
