### ISSUE TITLE
LaTex公式渲染失败

### ISSUE THREAD

**Issue by MrCaiDev** [auroral-ui/hexo-theme-aurora#130]
尝试了网上的很多方法，下了很多插件，包括issue里的[这篇](https://github.com/auroral-ui/hexo-theme-aurora/issues/55)，但还是没办法渲染，效果图如下：
![image](https://user-images.githubusercontent.com/78269445/129353125-fa36f7a2-13b5-4441-91c8-47d3a07af04d.png)

**Comment by MrCaiDev** [comment]
Use Math Block那里使用的是$$......$$，然后完全不显示任何内容

**Comment by bennyxguo** [comment]
你安装了 mathjax 了？
```shell
npm install hexo-filter-mathjax --save
```

然后有没有根据文档修改 `_config.yml`? 还有在你需要 mathjax 的文章的 front-meta 上添加参数？

详细看看这个包的文档：https://github.com/next-theme/hexo-filter-mathjax

**Comment by MrCaiDev** [comment]
重新检查了一遍，现在行内公式可以渲染了，但是公式块还是渲染不了，像这种：
![image](https://user-images.githubusercontent.com/78269445/129362811-15e09de5-5551-4dd0-ade1-846653e3f510.png)
网页上还是无内容，换了浏览器也不行。
这是我安装的插件：
![image](https://user-images.githubusercontent.com/78269445/129363032-1fbceec7-4d48-44a3-a2a5-3e7ac00df26a.png)

**Comment by MrCaiDev** [comment]
谢谢，把renderer-kramed换成renderer-pandoc之后问题解决了！
