### ISSUE TITLE
手机端打开首屏空白

### ISSUE THREAD

**Issue by duxinfeng** [auroral-ui/hexo-theme-aurora#131]
如图：

![IMG_1741](https://user-images.githubusercontent.com/8338102/129504750-550240f0-2c9d-476d-8a0f-2e48bdbda9a5.JPG)

**Comment by uyloal** [comment]
可以给出更多信息，方便定位。比如 config.yml 中的配置、是否有 post 等。

**Comment by duxinfeng** [comment]
> 可以给出更多信息，方便定位。比如 config.yml 中的配置、是否有 post 等。

不知道是不是和系统有关系，截图是主题的 demo  https://tridiamond.tech/ ，在设备是iPhone 8 Plus  13.3.1 Safari 和 Chrome 手机浏览器都这样，但是在另一台13.6.1 的iPhone XR 上就正常。
