### ISSUE TITLE
部分文章Latex公式渲染出现问题

### ISSUE THREAD

**Issue by 11D-Beyonder** [auroral-ui/hexo-theme-aurora#137]
已经安装 hexo-filter-mathjax，渲染器为  hexo-renderer-marked，部分文章mathjax为true时出错，部分文章mathjax为true时渲染正常。

[![hdH9US.png](https://z3.ax1x.com/2021/09/01/hdH9US.png)](https://imgtu.com/i/hdH9US)
其中一篇文章mathjax为false hexo g正常
[![hdHpE8.png](https://z3.ax1x.com/2021/09/01/hdHpE8.png)](https://imgtu.com/i/hdHpE8)
那篇文章mathjax为true，hexo g出错
[![hd7zHf.png](https://z3.ax1x.com/2021/09/01/hd7zHf.png)](https://imgtu.com/i/hd7zHf)
[![hdHC4g.png](https://z3.ax1x.com/2021/09/01/hdHC4g.png)](https://imgtu.com/i/hdHC4g)

如果先设置为false，再 hexo g,hexo s，显示正常，再将mathjax设置为true，再刷新也显示正常，但是关闭后再hexo g就出现上述情况。

初步排查发现是markdown文件中有 `&emsp;`等字符串导致渲染出现错误。

**Comment by bennyxguo** [comment]
这个应该是 hexo 插件的问题。
