### ISSUE TITLE
npm run serve报错

### ISSUE THREAD

**Issue by timmycheng** [auroral-ui/hexo-theme-aurora#139]
想改几个配置，比如header里的标题加一个“title”参数，但是fork了项目之后npm run serve报错
![image](https://user-images.githubusercontent.com/9245654/133254022-ac4f4f96-d2af-459e-bbe7-5bd5bef764f8.png)
不知道啥问题，有大佬帮帮忙嘛？

**Comment by littleboyfury** [comment]
添加这个配置
```
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.mjs$/,
          include: /node_modules/,
          type: "javascript/auto"
        }
      ]
    }
  },
```
