### ISSUE TITLE
使用vercel时的404问题

### ISSUE THREAD

**Issue by Lemonawa** [auroral-ui/hexo-theme-aurora#151]
打开一篇文章后,刷新便会404

**Comment by uyloal** [comment]
参考这个配置 https://github.com/auroral-ui/hexo-theme-aurora/issues/78#issuecomment-844790557

**Comment by Lemonawa** [comment]
> 
> 
> 参考这个配置 [#78 (comment)](https://github.com/auroral-ui/hexo-theme-aurora/issues/78#issuecomment-844790557)

可以了，感谢
