### ISSUE TITLE
文章设定description: 页面未生效

### ISSUE THREAD

**Issue by psily** [auroral-ui/hexo-theme-aurora#152]
这是文章上配置的截图：
![image](https://user-images.githubusercontent.com/28281142/143268415-f1d03459-202d-4aa9-91c2-4f22eda839c1.png)

这是结果截图：
![image](https://user-images.githubusercontent.com/28281142/143268518-0116989c-0ea2-4651-b60e-5161ba728869.png)

**Comment by bennyxguo** [comment]
2.0 版本已经加入该功能
