### ISSUE TITLE
gitalk 设置语言为cn仍旧显示英文

### ISSUE THREAD

**Issue by 11D-Beyonder** [auroral-ui/hexo-theme-aurora#155]
![QQ截图20211206034149.png](https://s2.loli.net/2021/12/06/6MJohj5SpEQGxeq.png)

![QQ截图20211206034048.png](https://s2.loli.net/2021/12/06/N9bPmDvlTZxo5GE.png)

**Comment by hachikozjq** [comment]
改成zh-CN
