### ISSUE TITLE
首页右侧信息卡没有内容

### ISSUE THREAD

**Issue by LjyLab** [auroral-ui/hexo-theme-aurora#160]
![image](https://user-images.githubusercontent.com/36144129/145683889-e379a21a-c3dd-4b86-b05a-2e075c4c3c0a.png)
在首页信息卡没有内容 而随便打开一个文章 右侧信息卡就有内容了

**Comment by uyloal** [comment]
配置了多个作者吗

**Comment by LjyLab** [comment]
> 配置了几个作者吗

已经解决啦 感谢回答

**Comment by githubforgth** [comment]
请问大佬是怎么解决的呀

**Comment by bennyxguo** [comment]
这个问题已经解决
