### ISSUE TITLE
这主题有bug啊，在任何一个页面重新刷新一下就会报404错误

### ISSUE THREAD

**Issue by xinghuostudio** [auroral-ui/hexo-theme-aurora#163]

**Comment by littleboyfury** [comment]
_posts 里面不要加子文件好像就没有问题，我是这样解决的，虽然感觉不太靠谱

**Comment by History-exe** [comment]
是不是你网络有问题，我就没有这个情况。

**Comment by Wangbaoqi** [comment]
github 部署的没有问题 其他托管网站如 vercel 就会有问题

**Comment by ahua666** [comment]
vercel 部署的我也是这个问题，本地访问没有这个问题

**Comment by znicelya** [comment]
我部署在腾讯云cos上也是这样，最后修改腾讯云配置解决
![image](https://user-images.githubusercontent.com/39379133/153700919-c6124da3-99b8-4a4a-b267-d9e0eeaa6b79.png)

**Comment by IversonTian** [comment]
> github 部署的没有问题 其他托管网站如 vercel 就会有问题

我用的github.io部署的 也有问题

**Comment by TTsdzb** [comment]
> vercel 部署的我也是这个问题，本地访问没有这个问题

Vercel 需要改一下，参考 [Vue 官方文档](https://router.vuejs.org/zh/guide/essentials/history-mode.html#Vercel)
