### ISSUE TITLE
代码高亮的括号太淡了，感觉修改一下会更好？

### ISSUE THREAD

**Issue by EmberIgor** [auroral-ui/hexo-theme-aurora#168]
![image](https://user-images.githubusercontent.com/48055760/148726893-261ef7e5-c9c9-4ccd-b909-59a1b22724c9.png)
不仔细看完全看不到有括号、大括号的存在，个人认为是不是让括号稍微明显一些会更好呢

**Comment by Ac-Accelerator** [comment]
> ![image](https://user-images.githubusercontent.com/48055760/148726893-261ef7e5-c9c9-4ccd-b909-59a1b22724c9.png) 不仔细看完全看不到有括号、大括号的存在，个人认为是不是让括号稍微明显一些会更好呢

可以自己改呀，在 \根目录\node_modules\hexo-theme-aurora\source\static\css\post.9f951a60.css里面可以调。

**Comment by idnewnil** [comment]
代码配色确实不是很好，我目前写代码都不指定它的语言，这样代码就是全部白色，虽然没配色但看起来也不错了。

**Comment by Satoing** [comment]
改css就可以，加上这样一个样式：
![image](https://user-images.githubusercontent.com/68995451/208382072-3ddd9d31-f146-4831-9d86-84f84a867757.png)
灰色渲染出来看起来还行，括号颜色就看你自己了
![image](https://user-images.githubusercontent.com/68995451/208382478-3c4a0f4f-f14d-4113-b832-3ac7407df721.png)

**Comment by ziqiang-wang-chn** [comment]
在\node_modules\hexo-theme-aurora\source\static\css\post.9f951a60.css里找到

.language-css .token.punctuation,
.language-html .token.punctuation,
.language-markup .token.punctuation,
.token.punctuation {
    /* color: var(--subs) */     原来的注释掉
    color: #f1e75d;    改一个自己喜欢的颜色
}

**Comment by bennyxguo** [comment]
Duplicate of #298
