### ISSUE TITLE
自定义页面之间不发生跳转以及 about 页面再刷新404

### ISSUE THREAD

**Issue by Fan223** [auroral-ui/hexo-theme-aurora#177]
1. 自定义了两个页面，一个 **留言板**，一个 **我的**，从 **留言板** 跳转到 **我的** 时，虽然路径发生了改变，但是不发生跳转，需要手动刷新页面才会跳转显示内容，而去非自定义的页面就可以，比如从 标签 到 留言板，留言板 到 标签。
2. 还有虽然文档说 about 页面是默认开启的，只需要创建目录就可以使用不需要配置，跳转和使用没问题，但是我在 **about 页面再刷新时会报404**，而不是和其他页面一样重新刷新回到这个页面

**Comment by znicelya** [comment]
![image](https://user-images.githubusercontent.com/39379133/158007136-decc89b8-a7a2-481a-9eea-c6006c51ba45.png)
about自己配置一个，他原有的有点问题

**Comment by Fan223** [comment]
那个自定义页面直接不发生跳转可以解决吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "auroral-ui/hexo-theme-aurora"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月12日(星期六) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [auroral-ui/hexo-theme-aurora] 自定义页面之间不发生跳转以及 about 页面再刷新404 (Issue #177)





 

 about自己配置一个，他原有的有点问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by panoshu** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/5207725/165522324-2662ba0c-6376-4498-bed2-13b114ce3c2a.png">
about页面上面要加一下 type: about，不然不会做特殊处理。

**Comment by Fan223** [comment]
> 

可以了。那个自定义的页面之间不发生跳转，地址变了，但是页面不发生改变，这个可以解决吗

**Comment by IversonTian** [comment]
> > 
> 
> 可以了。那个自定义的页面之间不发生跳转，地址变了，但是页面不发生改变，这个可以解决吗

请问您是如何解决的呢？

**Comment by IversonTian** [comment]
> <img alt="image" width="564" src="https://user-images.githubusercontent.com/5207725/165522324-2662ba0c-6376-4498-bed2-13b114ce3c2a.png">
> 
> about页面上面要加一下 type: about，不然不会做特殊处理。

是这样添加吗？
![image](https://user-images.githubusercontent.com/38484790/178403526-a3fe4b09-bc2b-4170-8ee0-441b947aa3a8.png)

**Comment by coderkpc** [comment]
> > <img alt="image" width="564" src="https://user-images.githubusercontent.com/5207725/165522324-2662ba0c-6376-4498-bed2-13b114ce3c2a.png">
> > about页面上面要加一下 type: about，不然不会做特殊处理。
> 
> 是这样添加吗？ ![image](https://user-images.githubusercontent.com/38484790/178403526-a3fe4b09-bc2b-4170-8ee0-441b947aa3a8.png)

![image](https://user-images.githubusercontent.com/91355573/188272920-02b1f043-7353-47d4-9658-ad9f21bc1180.png)
这样就可以了，你看看
