### ISSUE TITLE
自定义页面之间不发生跳转以及 about 页面再刷新404 bug

### ISSUE THREAD

**Issue by wjl110** [auroral-ui/hexo-theme-aurora#178]
自定义页面之间不发生跳转以及 about 页面再刷新404 bug

**Comment by bennyxguo** [comment]
Duplicate of #185

**Comment by wjl110** [comment]
thanks @bennyxguo

**Comment by wjl110** [comment]
permalink 配置了也会发生错误

**Comment by idnewnil** [comment]
about页面刷新的确会404，因为about页面实际上位于`/page/about/index.html`，但在浏览器刷新时会获取`/about`页面，所以不存在。可以尝试使用HTTP服务器进行重写，如果你用的是Caddy，那么可以加入以下语句。
```
@blog_about {
  host 博客域名
  path /about
}
rewrite @blog_about /page/about/index.html
```

**Comment by fffmath** [comment]
提供一个vercel的方案：
`
include:
'vercel.json'
exclude:
ignore:
&&
skip_render:
'vercel.json'
`

**Comment by TajangSec** [comment]
> include: 'vercel.json' exclude: ignore: && skip_render: 'vercel.json'

这句写哪里
