### ISSUE TITLE
valine能换成waline或者twikoo吗？

### ISSUE THREAD

**Issue by kyeo-hub** [auroral-ui/hexo-theme-aurora#181]
从作者的**obsidian**主题到**aurora**主题，作者一直喜欢 _valine_ 。**obsidian**还可以自己换，**aurora**用 _vue3_ 编写，我们这种小白完全不能改变（学习成本太高）
希望作者能把 _valine_ 评论系统换成 _twikoo_ 可以吗？实在不行 _waline_ 也行啊。
个人感觉 _twikoo_ 自定义空间更大一些，qq邮箱就能带出自己的 _avatar_ ，比 _gravatar_ 也更加实用一些。
> https://twikoo.js.org

**Comment by bennyxguo** [comment]
与这个一样 #230，已经在计划中
