### ISSUE TITLE
自定义页面（包括about页面）右边的profile信息无显示

### ISSUE THREAD

**Issue by kyeo-hub** [auroral-ui/hexo-theme-aurora#182]
![1647400547(1)](https://user-images.githubusercontent.com/44312958/158510018-ec5173c9-bd8d-4d1d-9b1d-54aa2e316f88.png)
![1647400788](https://user-images.githubusercontent.com/44312958/158510100-66feb9f7-7401-451d-b2d8-a0468a27979e.png)

**Comment by kyeo-hub** [comment]
浪费时间研究了两天，发现 #132 给出解决方案，还没验证，改天到公司再试一下。

**Comment by kyeo-hub** [comment]
经测试，有效！

**Comment by ITAurora** [comment]
> Author

你好 你是按照#132的pr改的吗 我按照他的代码添加混入后关于页面个人信息还是加载不出来
