### ISSUE TITLE
您好，我是使用Hexo npm install下载的您的主题，但是现在多作者情况下，Home下的作者信息一直在刷新

### ISSUE THREAD

**Issue by Vincent990413** [auroral-ui/hexo-theme-aurora#183]
您好，我是使用Hexo npm install下载的您的主题，但是现在多作者情况下，Home下的作者信息一直在刷新。

现在如何能够替换成您已经修复的版本呢？我看到您的源代码中已经修复，但苦于不知道如何替换成修复后的版本。我时使用Hexo clean Hexo s 直接生效的效果。不是通过Vue run build打包 谢谢您 有空请您回复一下

**Comment by G9doc8o** [comment]
同样的问题，坐等更新。

**Comment by Vincent990413** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by bennyxguo** [comment]
2.0 版本中修复了

**Comment by Vincent990413** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Vincent990413** [comment]
好的，感谢您的回复



---原始邮件---
发件人: "Benny ***@***.***&gt;
发送时间: 2023年7月24日(周一) 中午11:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [auroral-ui/hexo-theme-aurora] 您好，我是使用Hexo npm install下载的您的主题，但是现在多作者情况下，Home下的作者信息一直在刷新 (Issue #183)




 
2.0 版本中修复了
