### ISSUE TITLE
首页的文章卡片如何换背景图嘞

### ISSUE THREAD

**Issue by wanglei0917** [auroral-ui/hexo-theme-aurora#186]

**Comment by meemx** [comment]
修改.md文件里的cover就行

**Comment by wanglei0917** [comment]
![image](https://user-images.githubusercontent.com/65659854/164953658-53f6343d-1585-40b8-bd9a-a565e032943e.png)
大佬, 是这样设置吗? 我这样设置没效果呀

**Comment by wanglei0917** [comment]
感谢感谢

**Comment by KaSock** [comment]
问题解决了记得关闭Issues
