### ISSUE TITLE
首页卡片上的文字格式可不可以调整嘞, 

### ISSUE THREAD

**Issue by wanglei0917** [auroral-ui/hexo-theme-aurora#189]
现在首页文章卡片上的文字除了title, 剩下的就是文章内容挨个排的

**Comment by KaSock** [comment]
好像没有文章的description，预览demo里面的文章也都是靠文章前言当简述的..

**Comment by wanglei0917** [comment]
> 好像没有文章的description，预览demo里面的文章也都是靠文章前言当简述的..

好的吧....
