### ISSUE TITLE
按照文档安装，但是没有任何效果

### ISSUE THREAD

**Issue by asasas234** [auroral-ui/hexo-theme-aurora#194]
https://aurora.tridiamond.tech/zh/guide/getting-started.html
完全按这个文档安装的，但是当我访问localhost:4000 的时候还是默认的样式页面

```
hexo -version
INFO  Validating config
hexo: 6.2.0
hexo-cli: 4.3.0
os: darwin 21.4.0 12.3.1

node: 16.14.2
v8: 9.4.146.24-node.20
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1n+quic
cldr: 40.0
icu: 70.1
tz: 2021a3
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```

**Comment by wanglei0917** [comment]
你可以去仓库把主题拉下来放在本地 themes 文件夹里

**Comment by KaSock** [comment]
有没有可能是你_config.yml设置没改呢？
![image](https://user-images.githubusercontent.com/56071624/171562542-483e4480-c5fa-4470-8813-0a3f41dbd727.png)

**Comment by MunoDevelop** [comment]
> 有没有可能是你_config.yml设置没改呢？ ![image](https://user-images.githubusercontent.com/56071624/171562542-483e4480-c5fa-4470-8813-0a3f41dbd727.png)

thank you

**Comment by caoqinen** [comment]
> 有没有可能是你_config.yml设置没改呢？ ![image](https://user-images.githubusercontent.com/56071624/171562542-483e4480-c5fa-4470-8813-0a3f41dbd727.png)
谢谢
