### ISSUE TITLE
右侧信息栏里，标签还是0

### ISSUE THREAD

**Issue by asasas234** [auroral-ui/hexo-theme-aurora#196]
<img width="1635" alt="image" src="https://user-images.githubusercontent.com/4795442/168408263-528b231c-3a9a-4b69-97e1-bef7191efe6f.png">

我明明写标签了，在标签页也可以看到，但是在右侧信息里标签还是0

**Comment by asasas234** [comment]
@bennyxguo 作者帮忙看看？

**Comment by NING0121** [comment]
同上 @bennyxguo

**Comment by HelloEveryonehh** [comment]
我也遇到这个问题了，请问你们解决了吗？

**Comment by bennyxguo** [comment]
这个问题还存在吗？

**Comment by bennyxguo** [comment]
这个问题没有任何新进展，先关闭了。如果还有这个问题请重新提交 issue。谢谢

**Comment by czp-first** [comment]
还是有这个问题
