### ISSUE TITLE
cdn加速问题

### ISSUE THREAD

**Issue by bakenray** [auroral-ui/hexo-theme-aurora#200]
site_meta已经设置了cdn: cn了。但是项目运行起来，还都是请求cdn.jsdelivr.net的cdn加入，速度贼卡... 不知道为何没有按照文档所说，会切换到BootCDN。

**Comment by bakenray** [comment]
使用valine 插件后额外引入的，但是valine中没有配置这个cdn的配置....

**Comment by kcn3388** [comment]
可以试试自行修改对应的源文件URL

**Comment by bennyxguo** [comment]
在版本 2.0 已经全面换成了最新的 中国镜像 CDN。后面速度应该没有问题。但是 valine 中使用到的 leancloud 包，没有中国镜像。如果有朋友知道 leancloud 的中国镜像可以提供一下，我可以在下个版本更换上。
