### ISSUE TITLE
访问about关于和message-board留言板页面控制台报404 Not Found会在地址后自动添加一个null

### ISSUE THREAD

**Issue by IversonTian** [auroral-ui/hexo-theme-aurora#201]
![image](https://user-images.githubusercontent.com/38484790/177903252-7966a49d-e712-46f7-8467-e73522bf860a.png)
配置如下：
![image](https://user-images.githubusercontent.com/38484790/177903308-73d2a810-2151-42ca-b638-968c3fab90f5.png)
![image](https://user-images.githubusercontent.com/38484790/177903347-ef985736-68f8-47df-836a-b71eca90d2d9.png)

**Comment by IversonTian** [comment]
@bennyxguo 可以帮忙看看问题吗？

**Comment by kcn3388** [comment]
hexo 配置文件内的URL最后面加上'/'
Add a '/' in the end of url which in the config file of hexo itself.

**Comment by IversonTian** [comment]
> hexo 配置文件内的URL最后面加上'/' Add a '/' in the end of url which in the config file of hexo itself.

好的，我先试试，谢谢

**Comment by IversonTian** [comment]
> hexo 配置文件内的URL最后面加上'/' Add a '/' in the end of url which in the config file of hexo itself.

@kcn3388 还是有这个问题，但是页面是可以打开的，在about和message-board页面刷新页面会出现404
![image](https://user-images.githubusercontent.com/38484790/178198727-15292cd4-0094-4e2c-9268-3b49400c5d1f.png)

**Comment by IversonTian** [comment]
Hexo version如下：
![image](https://user-images.githubusercontent.com/38484790/178210822-e47eb41f-baae-4c68-af2f-8e214d5bec13.png)

**Comment by KaSock** [comment]
同样的问题
![image](https://user-images.githubusercontent.com/56071624/178638393-3685ad4c-3244-4d55-b9bb-e3c231f38e28.png)
而且我关于界面的作者信息出不来，手机界面侧边栏的作者信息也时不时挂掉
![image](https://user-images.githubusercontent.com/56071624/178638489-84609cc8-4d94-4f37-89c7-968e57ce431f.png)
版本
![image](https://user-images.githubusercontent.com/56071624/178639454-a9c8e9bc-5c7e-4dd3-a057-95237fabdcd0.png)

**Comment by KaSock** [comment]
看了下那个app.js null应该是手机端在获取的东西...

**Comment by kcn3388** [comment]
> 看了下那个app.js null应该是手机端在获取的东西...

先在Aurora文件夹做一次yarn install(npm install), yarn build(npm build)

**Comment by KaSock** [comment]
> > 看了下那个app.js null应该是手机端在获取的东西...
> 
> 先在Aurora文件夹做一次yarn install(npm install), yarn build(npm build)

npm yarn的东西没更新，我是克隆的仓库的

**Comment by KaSock** [comment]
暂时解决的方法：
修改app.js中的about页面path
第13处
![image](https://user-images.githubusercontent.com/56071624/178643146-15f2f6f9-3fa1-4797-a1aa-5dfd927c3828.png)

第15处
![image](https://user-images.githubusercontent.com/56071624/178643185-9badc545-7673-48d9-a502-fb53d28821f5.png)

**Comment by IversonTian** [comment]
> > 看了下那个app.js null应该是手机端在获取的东西...
> 
> 先在Aurora文件夹做一次yarn install(npm install), yarn build(npm build)

Aurora文件夹是指主题下clone的aurora项目吗？

**Comment by coderkpc** [comment]
![image](https://user-images.githubusercontent.com/91355573/188272957-e1fd2f93-cbe2-4dd4-b3e0-9e8d60a466e2.png)
这样p配置一下about页面就不会刷新404了

**Comment by KaSock** [comment]
> 

好家伙，解决了

**Comment by KaSock** [comment]
> ![image](https://user-images.githubusercontent.com/91355573/188272957-e1fd2f93-cbe2-4dd4-b3e0-9e8d60a466e2.png) 这样p配置一下about页面就不会刷新404了

好家伙，这样就解决了

**Comment by coderkpc** [comment]
> > ![image](https://user-images.githubusercontent.com/91355573/188272957-e1fd2f93-cbe2-4dd4-b3e0-9e8d60a466e2.png) 这样p配置一下about页面就不会刷新404了
> 
> 好家伙，这样就解决了

其实他讲的挺清楚的，就是你想错了，about页面本质上是个page，有一些meta属性，所以page.type应该是其中一个meta属性

**Comment by KaSock** [comment]
> > > ![image](https://user-images.githubusercontent.com/91355573/188272957-e1fd2f93-cbe2-4dd4-b3e0-9e8d60a466e2.png) 这样p配置一下about页面就不会刷新404了
> > 
> > 
> > 好家伙，这样就解决了
> 
> 其实在源码里面搜一下page.type就清楚的，about页面本质上是个page，有一些meta属性，所以page.type应该是其中一个meta属性

确实，我改js的做法和他源码里面的做法是一样的，都是改path为page/about了
![image](https://user-images.githubusercontent.com/56071624/188278882-64ebf46a-e5b4-4fd1-a682-fdc741960b89.png)

**Comment by zjcscut** [comment]
发现所有文章页面和about页面都会有个额外的请求，那个请求的格式是$uri/null，都报404，没找到这些请求是哪里发出来

**Comment by bennyxguo** [comment]
Duplicate of #151
