### ISSUE TITLE
如何关闭自定义about关于页面的评论功能

### ISSUE THREAD

**Issue by IversonTian** [auroral-ui/hexo-theme-aurora#202]
![image](https://user-images.githubusercontent.com/38484790/177903659-7a10e492-46f1-4708-97e0-105f56dcc2c7.png)
配置如下：
![image](https://user-images.githubusercontent.com/38484790/177903568-d16cc0ea-94af-4706-99f3-ab3f4d250d0a.png)

**Comment by IversonTian** [comment]
@bennyxguo

**Comment by kcn3388** [comment]
并未出现此问题
Can't see the same issue

**Comment by IversonTian** [comment]
> 并未出现此问题 Can't see the same issue

好了。谢谢

**Comment by IversonTian** [comment]
重新配置了下菜单 已解决
