### ISSUE TITLE
配置Mail Me页面后，点击无效果

### ISSUE THREAD

**Issue by IversonTian** [auroral-ui/hexo-theme-aurora#203]
![image](https://user-images.githubusercontent.com/38484790/177903914-13857523-5baa-4669-b403-133f39f33a48.png)
![image](https://user-images.githubusercontent.com/38484790/177903980-daf26c2a-337c-4512-a934-4c8c29d260a0.png)

**Comment by IversonTian** [comment]
@bennyxguo 可以看看吗？

**Comment by kcn3388** [comment]
模板没有写的功能不支持
We do not support functions which are not in the config template.

**Comment by IversonTian** [comment]
已解决
