### ISSUE TITLE
如何配置gitalk使用github登录功能

### ISSUE THREAD

**Issue by IversonTian** [auroral-ui/hexo-theme-aurora#204]
如题：
![image](https://user-images.githubusercontent.com/38484790/178198887-22019603-cdc2-4700-9dde-d4f8bb69bdda.png)
@bennyxguo

**Comment by IversonTian** [comment]
配置说明：
使用github的settings->developer settings->Oauth App创建一个App将其中的Client ID和生成的Client secrets配置到主题的gitalk配置对应的clientID和clientSecret就行

**Comment by IversonTian** [comment]
已解决

**Comment by aojiaodemeng** [comment]
只是配置clientID和clientSecret就好了吗？ 我配置之后显示error...
<img width="959" alt="image" src="https://github.com/auroral-ui/hexo-theme-aurora/assets/35892254/6a67eb9a-5168-4f86-bcc2-b89b4811b4f3">
