### ISSUE TITLE
请将将更改的内容发布到npm

### ISSUE THREAD

**Issue by ZHNLN0** [auroral-ui/hexo-theme-aurora#205]
npm 上的版本是 1.5.5 最新修改的内容并没有发布到 npm 包括 2022-4-17 的merge @bennyxguo 

- npm 版本更新时间 2021
![Snipaste_2022-07-12_22-41-24](https://user-images.githubusercontent.com/48152814/178518033-1a42df8c-4937-4880-9759-396aa8d02bac.png)

- 最新代码时间 2022-4-17
![Snipaste_2022-07-12_22-42-10](https://user-images.githubusercontent.com/48152814/178518251-496c9ddc-9318-4547-b8e4-81f3ba49dd79.png)

**Comment by Lisanity2019** [comment]
怕是等不来更新了，自己可以研究下自己打包

**Comment by bennyxguo** [comment]
已经发布了 2.0.0 谢谢支持
