### ISSUE TITLE
首页不蒜子游客访问量统计如何重置

### ISSUE THREAD

**Issue by bigbugboy** [auroral-ui/hexo-theme-aurora#212]
刚开始做主题的配置，遇到无法重置游客访问量重置的问题，期待大佬指导

配置如下：
![image](https://user-images.githubusercontent.com/63412071/184273161-8d3ddca2-465b-4c43-888a-0c711b5c8c03.png)

页面显示如下：
<img width="311" alt="image" src="https://user-images.githubusercontent.com/63412071/184273216-b9b90d7e-e496-4ab8-a0d5-95e89690fa3c.png">

**Comment by TTsdzb** [comment]
这个很大的数只是“127.0.0.1”的访问量，部署以后就是你网站的访问量了

这个计数器官网上写的是通过注册登录修改访问数，不过现在仍然没开放注册，可能只能通过更改域名的方式清零。
