### ISSUE TITLE
依照官方文档修改 无法使代码高亮

### ISSUE THREAD

**Issue by Lron-boy** [auroral-ui/hexo-theme-aurora#217]
![0066QMRGB`FR4LJY%G72FJT](https://user-images.githubusercontent.com/61782856/190947475-b376586f-d8ef-4e88-9db6-d9d1a31b61e1.jpg)
![M7SQ6 O$K%2W_U%B)NJHGM](https://user-images.githubusercontent.com/61782856/190947491-c73b5fa5-7849-4e71-9c91-b570527173ba.jpg)

**Comment by HelloEveryonehh** [comment]
我也遇到这个问题了，请问你解决这个问题了吗？

**Comment by Satoing** [comment]
手动改css？参考 #168

**Comment by bennyxguo** [comment]
看看控制台，是不是 prism 的 css 没有加载成功。

**Comment by TTsdzb** [comment]
使用 Hexo 7 就会出现这个问题，不清楚是什么原因导致的。我回退到 `6.3.0` 就正常了。

**Comment by bennyxguo** [comment]
> 使用 Hexo 7 就会出现这个问题，不清楚是什么原因导致的。我回退到 `6.3.0` 就正常了。

Hexo 7 目前还是 beta，插件很多都还不支持呢。先用 6.3.0+ 吧。谢谢你提供的信息。
