### ISSUE TITLE
文章链接太长导致超出容器

### ISSUE THREAD

**Issue by V21XY** [auroral-ui/hexo-theme-aurora#218]
![image](https://user-images.githubusercontent.com/63603770/192504423-fe86b81e-3b04-4dc0-9bf8-64e740ac7869.png)
如上图， 增加.post-html a 样式为 word-break: break-all; 可解决

**Comment by LuiYang08** [comment]
我也发现了这个问题，目前的解决办法好像就只有
[百度](https://www.baidu.com/)
而
[百度]<https://www.baidu.com/>
依旧会超出容器

**Comment by zechaowei** [comment]
我的目前也是，网页版就一篇博客出现了这种情况，其他的超长的就没有出现这个问题

**Comment by bennyxguo** [comment]
能发一下你们在线博客，有问题的那篇文章的地址吗？ @zechaowei

**Comment by LuiYang08** [comment]
> 能发一下你们在线博客，有问题的那篇文章的地址吗？ @zechaowei

[我都快忘了是怎么触发这个BUG的，但是很轻易就[复现了](https://luiyang08.github.io/post/hello-world)

**Comment by LuiYang08** [comment]
目前发现为，edge和chrome浏览器下无论pc还是android都会超出容器，而Firefox只有android会超出

**Comment by bennyxguo** [comment]
Fixed in 2.0.1
