### ISSUE TITLE
如何彻底删除评论相关模块

### ISSUE THREAD

**Issue by maohuifei** [auroral-ui/hexo-theme-aurora#219]
r t

**Comment by gongxuanzhang** [comment]
https://gongxuanzhang.github.io/post/aurora%E5%88%A0%E9%99%A4%E8%AF%84%E8%AE%BA%E4%BE%A7%E8%BE%B9%E6%A0%8F

**Comment by bennyxguo** [comment]
最新版本已经加入了该功能。
