### ISSUE TITLE
我没找到这个主题的Layout模板文件在哪个位置。

### ISSUE THREAD

**Issue by JChaooo** [auroral-ui/hexo-theme-aurora#221]
![image](https://user-images.githubusercontent.com/109884231/199495081-c4d140c0-dda7-429d-aed9-9a5fbf0582eb.png)

**Comment by Abyssaler** [comment]
找到了么，我也有同样的问题

**Comment by fez7yoe** [comment]
Hexo 根目錄有個 node_modules 資料夾
在該資料夾裡面找 hexo-theme-aurora
那個就是主題的資料夾

**Comment by bennyxguo** [comment]
`node_modules/hexo-theme-aurora/layout`
