### ISSUE TITLE
最近评论处的头像地址有问题

### ISSUE THREAD

**Issue by TTsdzb** [auroral-ui/hexo-theme-aurora#225]
如题，在博文底下的评论区，头像可以正常显示，在新标签页打开可以看到地址为 `https://gravatar.loli.net/avatar/16cfede0b72cb357a7e12f7167f5b410?d=identicon&v=1.4.9`。
![image](https://user-images.githubusercontent.com/62687036/208695865-1a451d1d-6d45-4676-9237-6a7178897b66.png)

但在首页的最近评论区域，这个地址变成了 `https://gravatar.loli.net/avatar/?d=identicon&v=1.5.5&16cfede0b72cb357a7e12f7167f5b410`。可以看出邮箱Hash跑到了最后面，导致获取不到头像。
![image](https://user-images.githubusercontent.com/62687036/208696006-cf6651ce-5bbd-4bbb-89d6-07baf96d72c9.png)

[博客地址](https://blog.ttsdzb.monster/)

**Comment by bennyxguo** [comment]
这个问题在版本 2.0 修复了，发布后可以根据文档升级哦！谢谢你的支持

**Comment by TTsdzb** [comment]
好的，感谢大佬！
