### ISSUE TITLE
主题首页文章卡片图片是如何生成的？

### ISSUE THREAD

**Issue by regulusleow** [auroral-ui/hexo-theme-aurora#232]
主题首页文章卡片图片是如何生成的？我在文档中没有看到怎么配置。难道是自动拾取？就是下图红框中的图片。我这边全部都是默认的钻石 icon。请问如何解决，感谢。

<img width="754" alt="image" src="https://user-images.githubusercontent.com/5687392/223327443-e1e7e2e2-5ee0-4e19-b806-4dc5d71713ae.png">

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/5687392/223327591-24e6ad6c-6b33-4547-a87d-5b02fbc75ad6.png">

**Comment by HarveyDawn** [comment]
在文章顶部添加`cover`: <图片链接> ，如下：
```
---
title: 
date: 
cover: https://xxx.png
--- 
```

**Comment by regulusleow** [comment]
> 在文章顶部添加`cover`: <图片链接> ，如下：
> 
> ```
> ---
> title: 
> date: 
> cover: https://xxx.png
> --- 
> ```

非常感谢
