### ISSUE TITLE
在文章详情页刷新会 Error

### ISSUE THREAD

**Issue by regulusleow** [auroral-ui/hexo-theme-aurora#233]
操作步骤：
1. 任意打开一篇文章（可以正常打开页面）
2. 按 cmd+r 刷新页面
3. 页面错误（部署到 github 同样复现）

报错信息如下图

<img width="843" alt="Xnip2023-03-10_20-10-51" src="https://user-images.githubusercontent.com/5687392/224312883-27c31805-ec61-4d88-8837-ef1dbc61b5fd.png">
<img width="1752" alt="Xnip2023-03-10_20-11-34" src="https://user-images.githubusercontent.com/5687392/224312943-27073838-890c-4da0-ab18-4f61ab2d7ab1.png">
<img width="1909" alt="Xnip2023-03-10_20-12-01" src="https://user-images.githubusercontent.com/5687392/224313038-855b6e3e-bdce-49e9-a8a6-78e11f347f4b.png">

**Comment by bennyxguo** [comment]
可以去 #185 找解决方案。
