### ISSUE TITLE
配置 gitalk 后，github 提示我敏感信息泄露

### ISSUE THREAD

**Issue by regulusleow** [auroral-ui/hexo-theme-aurora#234]
如下图

<img width="617" alt="image" src="https://user-images.githubusercontent.com/5687392/224314373-82584ef8-7634-4953-a647-95a3bd83b2bd.png">

**Comment by bennyxguo** [comment]
这个没有办法，gitalk 本来就是需要把 git token 放到代码中。只要你把你 git talk 的 token 的权限设置好就没有什么问题。如果还是担心，可以考虑用其他的评论系统哦。
