### ISSUE TITLE
归档（Archives）页面文章顺序错乱

### ISSUE THREAD

**Issue by TajangSec** [auroral-ui/hexo-theme-aurora#238]
我的归档页面文章顺序是乱的，**它既不是按照文章修改时间排序，也不是按照文章创建时间排序**。
**我的Mar 2023的文章甚至显示在2022的下面**，然后又有一部分2023文章在2022上面，图片里很清楚
归档的其他页也是如此，月份很乱
![FireShot Capture 008 - Archives - Tajang的大千世界 - rtbug com](https://user-images.githubusercontent.com/63721558/226133856-2b406ad9-c8f7-4698-9c56-2913057a5f7b.png)

**Comment by Satoing** [comment]
我之前解决过category和tag日期混乱的问题，你的问题应该也差不多。解决思路就是f12找到相应接口，然后在代码中对日期排序。参考 #223

**Comment by TajangSec** [comment]
> 我之前解决过category和tag日期混乱的问题，你的问题应该也差不多。解决思路就是f12找到相应接口，然后在代码中对日期排序。参考 #223

牛逼
