### ISSUE TITLE
同一个category在文章列表中归类成两个

### ISSUE THREAD

**Issue by Jeremy4455** [auroral-ui/hexo-theme-aurora#242]
如图，同一个CS category被分为两类文章，其中两篇还包含Algorithms category，另一篇只有CS category
![image](https://user-images.githubusercontent.com/92986854/232363209-df27e018-bcd2-4928-9ce7-3c2d24250ca1.png)

**Comment by Jeremy4455** [comment]
sorry, 说错了应该是categories

**Comment by Satoing** [comment]
这就是hexo的问题了。一篇文章只能设置一个category，如果有多个，hexo会认为后面的分类是前面的子分类。像你这样同名但父分类不同的也会被分开。
