### ISSUE TITLE
使用摘要功能

### ISSUE THREAD

**Issue by promefire** [auroral-ui/hexo-theme-aurora#246]
首页直接把正文全放上去了太难看了

**Comment by Satoing** [comment]
参考 #244

**Comment by bennyxguo** [comment]
这个功能我需要单独做，#244 使用了 JQuery。这个项目用的是 Vue 不推荐 JQuery 和 Vue 一起使用，会非常影响性能。

**Comment by bennyxguo** [comment]
这个功能已经在这里实现了，将会和主题版本 2.0.0 #249  一起发布 https://github.com/auroral-ui/hexo-plugin-aurora/commit/656ab3be21eff4141eef0e2a7acc90047a28a08d
