### ISSUE TITLE
文件列表会向右移动

### ISSUE THREAD

**Issue by eaveswww** [auroral-ui/hexo-theme-aurora#247]
文件列表中的文件名称，每次点击都会向右移动一格。电脑端可以通过点击调整文件列表窗口大小暂时复原，移动端（iOS）只能通过切换其他主题才能够恢复正常。很喜欢Aurora主题，希望可以修复解决。

![20230612145927](https://github.com/auroral-ui/hexo-theme-aurora/assets/135793043/a410dc48-9d89-4635-906d-05911d949189)

**Comment by Satoing** [comment]
不懂啥是文件列表……请你给出更详细的错误定位

**Comment by eaveswww** [comment]
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/135793043/f7fc3d1f-be6a-4d6a-9f8f-a1f519b72c63)

就是文件导航页面，按钮名称应该是【文件列表】，不过更新版本后暂时没问题了。我看网上也有其他人提出相关问题，可能是随机触发的bug。

**Comment by bennyxguo** [comment]
@eaveswww 你这个是 osidian 主题中的问题吧？这个问题在最新版本里面修复了。可以在 obsidian.md 的主题下载那里点击 “检查更新” 下载最新的版本就没事了。
