### ISSUE TITLE
Waline的最近评论时间计算出错

### ISSUE THREAD

**Issue by TTsdzb** [auroral-ui/hexo-theme-aurora#265]
可能与 #138（Valine）为相同问题。

最近评论中的评论时间与实际不一致，甚至可能出现 `NaN`。

最近评论中显示的评论：
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/62687036/e0aa9cf9-97af-4a39-9d82-87e7a0d475d5)

原文中显示的评论：
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/62687036/bf2a0eab-2678-46b9-87fc-c9540e1ed1a0)

在 <https://tridiamond.tech/> 中也能看到类似问题。

最近评论中显示的评论：
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/62687036/82fe2bf2-246e-48cd-872b-24400ab0cde8)

原文中显示的评论：
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/62687036/5fd27403-b9cf-42c4-af3c-508231820951)

**Comment by bennyxguo** [comment]
@TTsdzb 这里有两个问题：
1. 最近评论里面用了向上取整来计算时间，所以时间总是多了 1 分钟/小时/天/月/年。这个 PR #266 已经修复了这个问题
2. 第二个问题是来源于 waline 你部署的数据路的服务器当地时间。一般服务器都会把你的时间转成 UTC 时间。如果你不去设置 timezone 的话，是不会自动转换回 “北京” 时间的。但是你这里是 null 你就要看看你用到的数据库了，估计是你的时间类型有问题。

**Comment by TTsdzb** [comment]
出现 `NaN` 是由于 Waline 后端返回的 `insertedAt` 时间本身就有 `T`：

```json
{
    "nick": "TTsdzb",
    "insertedAt": "2023-08-04T02:14:48.798Z",
    "status": "approved",
    "link": "https://blog.ttsdzb.monster",
    "comment": "<p>评论一下吧~</p>\n",
    "url": "/post/hello-world",
    "objectId": "64cc5f1a7a64727f6c0b9c89",
    "browser": "Edge115.0",
    "os": "Windows 11",
    "avatar": "https://seccdn.libravatar.org/avatar/16cfede0b72cb357a7e12f7167f5b410",
    "orig": "评论一下吧~",
    "addr": "",
    "like": 0,
    "time": 1691115288798
}
```

再经过 `convertDateFormat` 方法后就不是需要的格式了。

我尝试了在项目 `index.js` 中添加 `process.env.TZ = 'Asia/Shanghai';` 来修改时区，但这个字段没有变化。

值得注意的是，服务器返回的 `time` 字段是对应的毫秒时间戳。能否直接通过这个来计算？这样看起来更方便合理一些。

**Comment by bennyxguo** [comment]
> 出现 `NaN` 是由于 Waline 后端返回的 `insertedAt` 时间本身就有 `T`：
> 
> ```json
> {
>     "nick": "TTsdzb",
>     "insertedAt": "2023-08-04T02:14:48.798Z",
>     "status": "approved",
>     "link": "https://blog.ttsdzb.monster",
>     "comment": "<p>评论一下吧~</p>\n",
>     "url": "/post/hello-world",
>     "objectId": "64cc5f1a7a64727f6c0b9c89",
>     "browser": "Edge115.0",
>     "os": "Windows 11",
>     "avatar": "https://seccdn.libravatar.org/avatar/16cfede0b72cb357a7e12f7167f5b410",
>     "orig": "评论一下吧~",
>     "addr": "",
>     "like": 0,
>     "time": 1691115288798
> }
> ```
> 
> 再经过 `convertDateFormat` 方法后得到 `'2023-08-04T02:14:48.798ZTundefined'`，就不是需要的格式了。
> 
> 我尝试了在项目 `index.js` 中添加 `process.env.TZ = 'Asia/Shanghai';` 来修改时区，但这个字段没有变化。
> 
> 值得注意的是，服务器返回的 `time` 字段是对应的毫秒时间戳。能否直接通过这个来计算？这样看起来更方便合理一些。

看来不同数据库返回的时间有点不一样。那么用 time 的这个可能会更好一些。应为这个时间戳应该是不会更具数据库而变的。
