### ISSUE TITLE
分类那我设置了 一直显示未分类

### ISSUE THREAD

**Issue by whiteRabbit-me** [auroral-ui/hexo-theme-aurora#280]
怀疑是不知道在哪写死的吧  或者是配置的那有问题 怎么解决
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/87886741/12643cf1-438e-45e4-aaea-2cb03bfa182b)
还有头像问题 第一个板块可以显示 后面的显示不出来
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/87886741/a9821cc5-8b4e-40fe-978c-3fbc5e4a5f1d)

请问我该怎么解决

**Comment by whiteRabbit-me** [comment]
还是说我需要去改动源码 在配合hexo使用

**Comment by whiteRabbit-me** [comment]
还有看文档说设置这个feature: true就是推荐
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/87886741/ae9833c9-0d1d-44b8-bbb8-20e01616a3af)
下面是我设置的
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/87886741/29514b93-2ddf-41b1-af85-93e6fe8ccfed)
发现没有起作用 还是说我设置错了

**Comment by whiteRabbit-me** [comment]
我使用了评论插件 也成功了 但是首页上的最近评论我改如何设置  文档中似乎没有找到啊

发现我遇到的问题还挺多 我太菜了

**Comment by bennyxguo** [comment]
> 还有看文档说设置这个feature: true就是推荐 ![image](https://user-images.githubusercontent.com/87886741/259695818-ae9833c9-0d1d-44b8-bbb8-20e01616a3af.png) 下面是我设置的 ![image](https://user-images.githubusercontent.com/87886741/259696037-29514b93-2ddf-41b1-af85-93e6fe8ccfed.png) 发现没有起作用 还是说我设置错了

你的格式有问题

```markdown
---
title: Win-Inux
date: 2023-08-10 13:48:58
categories:
  - web前端 # 这里注意一定要有两个空格
feature: true
---
```

**Comment by whiteRabbit-me** [comment]
> 

gitalk:
  enable: true
  autoExpand: true
  clientID: '1d4449a3eeabd69d9358'
  clientSecret: '507aa31fbcde2e460169ffd927e2e3716e286de7'
  repo: 'whiteRabbit-me.github.io'
  owner: 'whiteRabbit-me'
  admin: ['whiteRabbit-me']
  id: uid
  language: cn
  distractionFreeMode: true
  recentComment: true
  proxy: ''
这个recentComment属性设置了true 
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/87886741/83f09892-0ece-42ec-9942-c7063bf198b0)
评论也有了
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/87886741/9cbed309-2fb7-4d44-8d7f-835a304908d5)
这是我遇到的情况

**Comment by whiteRabbit-me** [comment]
第二个问题就是site:
  subtitle: whiteRabbit's Blog
  author: 白兔
  nick: whiteRabbit
  description: 一只刚刚入门的小白兔
  language: cn
  multi_language: true
  logo: https://img-blog.csdnimg.cn/20210313122054101.png
  avatar: https://img-blog.csdnimg.cn/20210313122054101.png
  beian:
    number: ''
    link: ''
  police_beian:
    number: ''
    link: ''
  started_date: # Start date of the blog YYY-MM-DD / 博客开始运行日期
这个logo显示有问题 这个url也有图片 但是加载不出来
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/87886741/07c86d1e-ab5d-41bc-9447-8d9d6f759248)

**Comment by whiteRabbit-me** [comment]
留言版功能是不是只有我才能记录  是吧  那我就剩上面遇到的2个问题了

**Comment by bennyxguo** [comment]
> 第二个问题就是site: subtitle: whiteRabbit's Blog author: 白兔 nick: whiteRabbit description: 一只刚刚入门的小白兔 language: cn multi_language: true logo: https://img-blog.csdnimg.cn/20210313122054101.png avatar: https://img-blog.csdnimg.cn/20210313122054101.png beian: number: '' link: '' police_beian: number: '' link: '' started_date: # Start date of the blog YYY-MM-DD / 博客开始运行日期 这个logo显示有问题 这个url也有图片 但是加载不出来 ![image](https://user-images.githubusercontent.com/87886741/259914611-07c86d1e-ab5d-41bc-9447-8d9d6f759248.png)

不要用 csdn 的图片，它们控制了不能再它们域名之外使用的。我这边也打不开你的图片。

<img width="941" alt="image" src="https://github.com/auroral-ui/hexo-theme-aurora/assets/24708758/06036634-ebdd-4cdc-bd11-733dfca1af03">

**Comment by whiteRabbit-me** [comment]
> 

这个明白了 感谢博主  博主看看我的那个评论是配置错了吗 最近评论显示不出来

**Comment by bennyxguo** [comment]
> > 
> 
> 这个明白了 感谢博主 博主看看我的那个评论是配置错了吗 最近评论显示不出来

那个你发布到 github pages 发链接给我看看吧

**Comment by whiteRabbit-me** [comment]
> > > 
> > 
> > 
> > 这个明白了 感谢博主 博主看看我的那个评论是配置错了吗 最近评论显示不出来
> 
> 那个你发布到 github pages 发链接给我看看吧
https://whiterabbit-me.github.io/

**Comment by bennyxguo** [comment]
> > > > 
> > > 
> > > 
> > > 这个明白了 感谢博主 博主看看我的那个评论是配置错了吗 最近评论显示不出来
> > 
> > 
> > 那个你发布到 github pages 发链接给我看看吧
> > https://whiterabbit-me.github.io/

最近评论无法显示的问题找到了，是 gitalk 的 loading state 没有关闭。这个 issue 会修复这个问题 #290

**Comment by whiteRabbit-me** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 这个明白了 感谢博主 博主看看我的那个评论是配置错了吗 最近评论显示不出来
> > > 
> > > 
> > > 那个你发布到 github pages 发链接给我看看吧
> > > https://whiterabbit-me.github.io/
> 
> 最近评论无法显示的问题找到了，是 gitalk 的 loading state 没有关闭。这个 issue 会修复这个问题 #290

好的 感谢博主
