### ISSUE TITLE
TypeError: truncate.setup is not a function

### ISSUE THREAD

**Issue by Mristoforo** [auroral-ui/hexo-theme-aurora#283]
INFO  Validating config
ERROR Plugin load failed: hexo-plugin-aurora
TypeError: truncate.setup is not a function

**Comment by bennyxguo** [comment]
You need to install both `hexo-theme-aurora` and `hexo-plugin-aurora`
e.g:
```
npm install hexo-theme-aurora hexo-plugin-aurora
```
