### ISSUE TITLE
Dia问题

### ISSUE THREAD

**Issue by yiqikeji** [auroral-ui/hexo-theme-aurora#292]
当按照文档所写的样子去配置dia，dia就不会在首页显示，将tips后全部删除又可以显示了，这个是怎么回事
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/68860562/d9ba4fad-8a6d-4094-b8f5-f6de7cb6ac1a)

**Comment by Tim-Saijun** [comment]
Aurora v2.4.3 遇到了同样的问题
![639cb3a9a903c5a6a53b8537b6fadba5](https://github.com/auroral-ui/hexo-theme-aurora/assets/76874480/751e9d60-6037-4a91-b92b-673123722c7f)
机器人无法自定义，加上图里这段配置机器人就没了，错误如下图：
![eb6cab026bc3b5b1790cf7373e39f791](https://github.com/auroral-ui/hexo-theme-aurora/assets/76874480/c8950ed9-255b-4b41-b703-53ba58287ebd)
但是，如果仅保留tips以上的配置，就没问题
