### ISSUE TITLE
文档更新建议

### ISSUE THREAD

**Issue by Sang-Buster** [auroral-ui/hexo-theme-aurora#293]
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/97267956/a85f2632-358b-4ba4-86e4-16e6c39565e1)

> What is next?
There are two places you should check out next:
Setting up your [Page](https://aurora.tridiamond.tech/guide/page.html)
Advance [configurations](https://aurora.tridiamond.tech/guide/configuration.html) document

- Page 和 configuration 是404页面.

---

在hexo最新版本 v6.3.0， hexo-cli v4.3.1，以下命令
```shell
hexo create page about
hexo create page message-board
hexo create page links
```
是不行了， 需更改/添加
```shell
hexo new page about
hexo new page message-board
hexo new page links
```

目前就 `guide/getting-started.html#step-5-setting-up-code-highlight` 和 `configs/page.html`  两个页面需要额外添加上面的命令。

**Comment by bennyxguo** [comment]
谢谢呀，记录了

**Comment by bennyxguo** [comment]
已经更新了
