### ISSUE TITLE
Feature request: Allow to change favicon

### ISSUE THREAD

**Issue by CodingJellyfish** [auroral-ui/hexo-theme-aurora#299]
The original favicon does not fit after the gradient color is changed.

**Comment by bennyxguo** [comment]
Which logo? You can configure the logo in the config.

**Comment by CodingJellyfish** [comment]
> Which logo? You can configure the logo in the config.

Sorry for my unclear explanation. The title has changed.

**Comment by CodingJellyfish** [comment]
My fault.
