### ISSUE TITLE
The mobile menu disappears with other components misplaced when transforming window size with mobile menu on

### ISSUE THREAD

**Issue by CodingJellyfish** [auroral-ui/hexo-theme-aurora#302]
This is a bit hard to explain. See video below:

https://github.com/auroral-ui/hexo-theme-aurora/assets/35170687/f9d15a18-dced-438e-9aff-7c9c742ea062

**Comment by bennyxguo** [comment]
This is by design not misplaced.

**Comment by bennyxguo** [comment]
Mobile menu had completely changed since latest update. #315
