### ISSUE TITLE
更新前后UI大小大概差了有10%，是更新内容吗？

### ISSUE THREAD

**Issue by LuiYang08** [auroral-ui/hexo-theme-aurora#307]
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/69292505/314d1b17-1775-4810-b22f-f13f82a629e2)
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/69292505/dd71db3e-345e-4adf-98fa-be44977f9a0e)

图1为更新前的2.0.1版本，图2为更新后的2.3.1版本。
更新前后UI大小大概差了有10%，是更新内容吗？

**Comment by LuiYang08** [comment]
且发现首推文章的 # 标签失效了，本人并未有其他更改

**Comment by bennyxguo** [comment]
对的，是放大了UI，特别是文字。博客类型的网站，字体在 14px 的基础太小了。阅读起来很费眼睛。看考了几个大平台，它们都是用 16px 的基数的。所以整体调整过了阅读舒适度。

关于标签的消失，发一下你博客的 URL 我去看看。

**Comment by LuiYang08** [comment]
https://luiyang08.github.io/

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Benny Guo ***@***.***>
发送时间: Tuesday, August 15, 2023 5:46:40 PM
收件人: auroral-ui/hexo-theme-aurora ***@***.***>
抄送: ***@***.*** ***@***.***>; Author ***@***.***>
主题: Re: [auroral-ui/hexo-theme-aurora] 更新前后UI大小大概差了有10%，是更新内容吗？ (Issue #307)


对的，是放大了UI，特别是文字。博客类型的网站，字体在 14px 的基础太小了。阅读起来很费眼睛。看考了几个大平台，它们都是用 16px 的基数的。所以整体调整过了阅读舒适度。

关于标签的消失，发一下你博客的 URL 我去看看。

―

**Comment by LuiYang08** [comment]
另外侧边栏的评论区，字体貌似没有跟随您的改动而变动，相对之下看起来有点怪？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Benny ***@***.***>
发送时间: 2023年8月15日 17:46
收件人: ***@***.***>
抄送: ***@***.******@***.***>; ***@***.***>
主题: Re: [auroral-ui/hexo-theme-aurora] 更新前后UI大小大概差了有10%，是更新内容吗？ (Issue #307)


对的，是放大了UI，特别是文字。博客类型的网站，字体在 14px 的基础太小了。阅读起来很费眼睛。看考了几个大平台，它们都是用 16px 的基数的。所以整体调整过了阅读舒适度。

关于标签的消失，发一下你博客的 URL 我去看看。

―
