### ISSUE TITLE
UI enhancement for sidebar, tags and pagination

### ISSUE THREAD

**Issue by bennyxguo** [auroral-ui/hexo-theme-aurora#314]

**Comment by Sang-Buster** [comment]
还有隐藏评论 comments: false应该不单单隐藏评论应该把整个评论区隐藏

**Comment by bennyxguo** [comment]
> 还有隐藏评论 comments: false应该不单单隐藏评论应该把整个评论区隐藏，以及手机模式下menu点一下右边地方就收回的功能

我看过代码了都是整个隐藏的。

**Comment by Sang-Buster** [comment]
> > 还有隐藏评论 comments: false应该不单单隐藏评论应该把整个评论区隐藏，以及手机模式下menu点一下右边地方就收回的功能
> 
> 我看过代码了都是整个隐藏的。

啊这 我这边是没有隐藏的， 只隐藏了评论
