### ISSUE TITLE
2.4.0版本post页面问题

### ISSUE THREAD

**Issue by Sang-Buster** [auroral-ui/hexo-theme-aurora#322]
在comments: false情况下，post的页面浏览数 那团火旁边的数字是黑色的

**Comment by Sang-Buster** [comment]
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/97267956/f87c1884-be85-48e1-a45b-e7f8e82f1c99)

英文引号莫名其妙会变成中文引号，我回到之前的版本是没有问题

**Comment by bennyxguo** [comment]
你说的两个问题都无法重现
<img width="763" alt="image" src="https://github.com/auroral-ui/hexo-theme-aurora/assets/24708758/3d8c791e-ba07-4793-a63e-483e340fbed4">

**Comment by Sang-Buster** [comment]
![Screenshot 2023-08-23 134025](https://github.com/auroral-ui/hexo-theme-aurora/assets/97267956/10d491e1-ab90-4c6a-bca6-d44158b74feb)

这个是这样的, 如果`comments:false`, 浏览数字在火旁边是黑色方块

**Comment by Sang-Buster** [comment]
> 你说的两个问题都无法重现 <img alt="image" width="763" src="https://user-images.githubusercontent.com/24708758/262751275-3d8c791e-ba07-4793-a63e-483e340fbed4.png">

我也不知道为啥我这里是这样， 好像是`hexo-renderer-marked`的问题，下面的code加在`_config.yml`能让post里面的引号修复，但是问题还是在table里面
```
marked:
  smartypants: false
```
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/97267956/baf5740a-62b9-4248-8203-0bd7a3a346aa)

**Comment by Sang-Buster** [comment]
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/97267956/958bd423-9eb1-4a6f-9f51-3c266186c387)

发现了另外一个小bug， callout message/custom container 的list bullet point 好像是居中处理的，但是如果是平常的text bullet point 太长了它就会图片里的

效果应该如下：
- It is required to leave a name and a valid email address, so that you can receive a timely reply from me/each others.
- Feel free to leave a comment if you have any questions/suggestions about the content of this site.
- Please leave friendly messages for each other within the course content.

**Comment by bennyxguo** [comment]
@Sang-Buster 我这边复现不了。可以提供一下你的源码吗？

![Image](https://github.com/auroral-ui/hexo-theme-aurora/assets/24708758/3e0a077b-57cb-4307-8d95-dad980f4a4cc)

**Comment by Sang-Buster** [comment]
> @Sang-Buster 我这边复现不了。可以提供一下你的源码吗？
> 
> ![Image](https://user-images.githubusercontent.com/24708758/268137492-3e0a077b-57cb-4307-8d95-dad980f4a4cc.png)
> 
> ```
> :::tip
> 
> - It is required to leave a name and a valid email address, so that you can receive a timely reply from me/each other. It is required to leave a name and a valid email address, so that you can receive a timely reply from me/each others.
> - Feel free to leave a comment if you have any questions/suggestions about the content of this site.
> - Please leave friendly messages for each other within the course content.
> 
> :::
> ```

我升级到最新的，发现这个问题解决了， 我也复现不了😂

**Comment by bennyxguo** [comment]
不知不觉解决了，太棒了 🤣
