### ISSUE TITLE
在墙内今天突然无法打开博客了，页面一片空白

### ISSUE THREAD

**Issue by joshleeeeee** [auroral-ui/hexo-theme-aurora#342]
如下图所示，[waline库](https://unpkg.com/@waline/client@v2/dist/waline.mjs)被墙了，导致在墙内无法访问博客，一访问博客就直接页面空白无任何响应，很突然，今天才开始才这样的

<img width="1095" alt="image" src="https://github.com/auroral-ui/hexo-theme-aurora/assets/62055946/78d984cb-28db-43c9-a092-3215a9d7351c">

Version: 2.4.3

**Comment by joshleeeeee** [comment]
准确来说是 [unpkg.com](https://unpkg.com) 被墙了

**Comment by bennyxguo** [comment]
这个没有办法，不是我能控制的，unpack 在国内已经比较稳定的一个了。

**Comment by joshleeeeee** [comment]
说下我自己在本地（Mac）的解决方案吧
1. 把[waline.mjs](https://unpkg.com/@waline/client@v2/dist/waline.mjs)下载到本地，并放进 `/source/asset/waline.mjs`
2. 用终端工具 cd到 `./node_modules/hexo-theme-aurora/source/static/js`文件夹内
3. 输入下面命令将当前目录下所有 js 文件中的 waline 库的 url 替换为`/asset/waline.mjs`
``` bash
find . -name "*.js" -exec sed -i '' 's#https://unpkg.com/@waline/client@v2/dist/waline.mjs#/asset/waline.mjs#g' {} +
```
4. 大功告成
