### ISSUE TITLE
个人资料卡上的个签在哪里修改？

### ISSUE THREAD

**Issue by vanhiupun** [auroral-ui/hexo-theme-aurora#345]
![问题1](https://github.com/auroral-ui/hexo-theme-aurora/assets/89436345/c72c8851-edc5-474a-92f0-9af2b55a32c3)

**Comment by HulaHula20072109** [comment]
In file '_config.aurora.yml'
site:
|_ subtitle:
|_ ...
|_ description: Programming a piece of art  <-- Here
|_ ...
