### ISSUE TITLE
能否提供静态资源本地化的选项

### ISSUE THREAD

**Issue by zjcscut** [auroral-ui/hexo-theme-aurora#346]
部分静态资源使用的CDN不稳定，特别是字体文件。能否提供选项本地化打包所有依赖的js、css和字体文件，直接打包输出到public目录下下，这样就能一起放到腾讯云COS或者阿里云OSS上

**Comment by bennyxguo** [comment]
这样就没有办法使用 CDN 加速了。页面首次加载也会大大变慢的。

**Comment by zjcscut** [comment]
@zjcscu

> 这样就没有办法使用 CDN 加速了。页面首次加载也会大大变慢的。

OK，那先关闭这个issue
