### ISSUE TITLE
A suggestion of Highlight

### ISSUE THREAD

**Issue by HulaHula20072109** [auroral-ui/hexo-theme-aurora#349]
An amazing theme based on hexo !
But it looks like the current version doesn't work with prismjs themes. It would be better if adding more hightlight themes.
Or users can load .css/.js file by themselves.

**Comment by HulaHula20072109** [comment]
In addition, the the current version do not support line_number option. I'm not sure whether my configuration is right:
highlight:
  enable: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

**Comment by bennyxguo** [comment]
Thanks you for your support! Yeah I am planning on adding the option to change Prism themes.

**Comment by bennyxguo** [comment]
replicate #298

**Comment by Tim-Saijun** [comment]
很需要的改进，如果能在右上角一键复制就更好了
