### ISSUE TITLE
友链页面的JSON链接不到

### ISSUE THREAD

**Issue by LuiYang08** [auroral-ui/hexo-theme-aurora#355]
![`{ NT)(QZQ~0V@GY7 FQY N](https://github.com/auroral-ui/hexo-theme-aurora/assets/69292505/976ea21a-2cc1-4f0b-b7df-b61bb060eca1)

![2TT W$%Q@~5
UV749AF)(P](https://github.com/auroral-ui/hexo-theme-aurora/assets/69292505/bc17c7ba-c093-4369-9f6a-9277862090bf)

友链页面的JSON链接不到

**Comment by Tim-Saijun** [comment]
这是配置文档里的问题，友链页面应该在friends文件夹下，而不是links文件夹下
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/76874480/86c7c306-a6d4-4673-b1bc-dd10c747911d)
**将友链的links文件夹重命名为friends即可**

**Comment by LuiYang08** [comment]
哦哦哦，确实，改了之后OK了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Tim Yang ***@***.***>
发送时间: Friday, September 8, 2023 9:38:55 PM
收件人: auroral-ui/hexo-theme-aurora ***@***.***>
抄送: ***@***.*** ***@***.***>; Author ***@***.***>
主题: Re: [auroral-ui/hexo-theme-aurora] 友链页面的JSON链接不到 (Issue #355)


这是配置文档里的问题，友链页面应该在friends文件夹下，而不是links文件夹下
[image]<https://user-images.githubusercontent.com/76874480/266627565-86c7c306-a6d4-4673-b1bc-dd10c747911d.png>
将友链的links文件夹重命名为friends即可

―
