### ISSUE TITLE
Unable to update Twikoo plugin version.

### ISSUE THREAD

**Issue by Sang-Buster** [auroral-ui/hexo-theme-aurora#356]
I'm always frustrated when Twikoo Comment Plugin is not up to date.

**Describe the solution you'd like**
Being able to use the most up to date version of Twikoo, current newest version `1..6.19`, Aurora only stays at `v1.6.17`

**Comment by bennyxguo** [comment]
In next version of hexo-plugin-aurora. All plguin will auto use the lastet minor versions. @Sang-Buster
