### ISSUE TITLE
进入文章之后，在文章页面再刷新就404

### ISSUE THREAD

**Issue by B3r1aL** [auroral-ui/hexo-theme-aurora#395]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] (是否与都个问题有有关，请详细描述)

**Describe the solution you'd like**
A clear and concise description of what you want to happen.（描述想要的效果）

**Additional context or screenshots**
Add any other context or screenshots about the feature request here.（附加信息或者截图）

**Comment by bennyxguo** [comment]
Duplicate of #185 

请款 issu #185
