### ISSUE TITLE
当根目录的prismjs和highlight为false，主题shiki代码高亮为true报错

### ISSUE THREAD

**Issue by try-to-change** [auroral-ui/hexo-theme-aurora#398]
**Is your feature request related to a problem? Please describe.**
当我按照文档对配置文件进行修改highlight，prismjs都为false
但是打开主题的代码高亮选项shiki， 就发生了报错

**Describe the solution you'd like**
但之前有一次好像是正常显示，然后后面再试不行了

**Additional context or screenshots**
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/106241874/269585b1-ca69-433a-88c0-eedb3184f258)
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/106241874/0caffe11-0a2a-4184-b6a1-45f59f6c24f9)

**Comment by Tim-Saijun** [comment]
hexo-plugin-aurora v1.8.3 & hexo-theme-aurora v2.5.2
相同的配置
```yml
highlight:
  enable: false
  # line_number: true
  # auto_detect: false
  # tab_replace: ''
  # wrap: true
  # hljs: false
prismjs:
  enable: false
  # preprocess: false
  # line_number: true
  # tab_replace: ''
```
```yml
#! ---------------------------------------------------------------
#! Highlighter Shiki
#! ---------------------------------------------------------------
shiki:
  enable: true
  theme: vitesse-dark
  backgroundColor: '#1a1a1a'
```
generate无报错，控制台无报错，就是不亮（多种语言）

**Comment by bennyxguo** [comment]
> **Is your feature request related to a problem? Please describe.** 当我按照文档对配置文件进行修改highlight，prismjs都为false 但是打开主题的代码高亮选项shiki， 就发生了报错
> 
> **Describe the solution you'd like** 但之前有一次好像是正常显示，然后后面再试不行了
> 
> **Additional context or screenshots** ![image](https://user-images.githubusercontent.com/106241874/276641228-269585b1-ca69-433a-88c0-eedb3184f258.png) ![image](https://user-images.githubusercontent.com/106241874/276640575-0caffe11-0a2a-4184-b6a1-45f59f6c24f9.png)

你这个属于代码块里面有语法错误。

**Comment by bennyxguo** [comment]
> hexo-plugin-aurora v1.8.3 & hexo-theme-aurora v2.5.2 相同的配置
> 
> ```yaml
> highlight:
>   enable: false
>   # line_number: true
>   # auto_detect: false
>   # tab_replace: ''
>   # wrap: true
>   # hljs: false
> prismjs:
>   enable: false
>   # preprocess: false
>   # line_number: true
>   # tab_replace: ''
> ```
> 
> ```yaml
> #! ---------------------------------------------------------------
> #! Highlighter Shiki
> #! ---------------------------------------------------------------
> shiki:
>   enable: true
>   theme: vitesse-dark
>   backgroundColor: '#1a1a1a'
> ```
> 
> generate无报错，控制台无报错，就是不亮（多种语言）

有源代码的链接吗？还有你的网站上线了吗？有博客的地址吗？

**Comment by Tim-Saijun** [comment]
> > hexo-plugin-aurora v1.8.3 & hexo-theme-aurora v2.5.2 相同的配置
> > ```yaml
> > highlight:
> >   enable: false
> >   # line_number: true
> >   # auto_detect: false
> >   # tab_replace: ''
> >   # wrap: true
> >   # hljs: false
> > prismjs:
> >   enable: false
> >   # preprocess: false
> >   # line_number: true
> >   # tab_replace: ''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```yaml
> > #! ---------------------------------------------------------------
> > #! Highlighter Shiki
> > #! ---------------------------------------------------------------
> > shiki:
> >   enable: true
> >   theme: vitesse-dark
> >   backgroundColor: '#1a1a1a'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > generate无报错，控制台无报错，就是不亮（多种语言）
> 
> 有源代码的链接吗？还有你的网站上线了吗？有博客的地址吗？

https://www.zair.top

**Comment by TTsdzb** [comment]
> hexo-plugin-aurora v1.8.3 & hexo-theme-aurora v2.5.2 相同的配置
> 
> ```yaml
> highlight:
>   enable: false
>   # line_number: true
>   # auto_detect: false
>   # tab_replace: ''
>   # wrap: true
>   # hljs: false
> prismjs:
>   enable: false
>   # preprocess: false
>   # line_number: true
>   # tab_replace: ''
> ```
> 
> ```yaml
> #! ---------------------------------------------------------------
> #! Highlighter Shiki
> #! ---------------------------------------------------------------
> shiki:
>   enable: true
>   theme: vitesse-dark
>   backgroundColor: '#1a1a1a'
> ```
> 
> generate无报错，控制台无报错，就是不亮（多种语言）

如果使用 `hexo@7.0.0`，回退到 `6.3.0` 试一下

**Comment by Tim-Saijun** [comment]
> > hexo-plugin-aurora v1.8.3 & hexo-theme-aurora v2.5.2 相同的配置
> > ```yaml
> > highlight:
> >   enable: false
> >   # line_number: true
> >   # auto_detect: false
> >   # tab_replace: ''
> >   # wrap: true
> >   # hljs: false
> > prismjs:
> >   enable: false
> >   # preprocess: false
> >   # line_number: true
> >   # tab_replace: ''
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```yaml
> > #! ---------------------------------------------------------------
> > #! Highlighter Shiki
> > #! ---------------------------------------------------------------
> > shiki:
> >   enable: true
> >   theme: vitesse-dark
> >   backgroundColor: '#1a1a1a'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > generate无报错，控制台无报错，就是不亮（多种语言）
> 
> 如果使用 `hexo@7.0.0`，回退到 `6.3.0` 试一下

检查过了
```json
  "hexo": {
    "version": "6.3.0"
  },
```

**Comment by bennyxguo** [comment]
可以看看是否有插件和 aurora 的生成器插件冲突了。看看这里 https://github.com/auroral-ui/hexo-theme-aurora/issues/390#issuecomment-1789511301

**Comment by cyl-ly** [comment]
> **Is your feature request related to a problem? Please describe.** 当我按照文档对配置文件进行修改highlight，prismjs都为false 但是打开主题的代码高亮选项shiki， 就发生了报错
> 
> **Describe the solution you'd like** 但之前有一次好像是正常显示，然后后面再试不行了
> 
> **Additional context or screenshots** ![image](https://private-user-images.githubusercontent.com/106241874/276641228-269585b1-ca69-433a-88c0-eedb3184f258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzA3MDUsIm5iZiI6MTcwMzQ3MDQwNSwicGF0aCI6Ii8xMDYyNDE4NzQvMjc2NjQxMjI4LTI2OTU4NWIxLWNhNjktNDMzYS04OGMwLWVlZGIzMTg0ZjI1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTE1NWNlZWQ5NTUyMGU5ZGZmYjg5ZDM5MDI4MWZlYzYxYzU3NGM0ZTI3ZjNmYjJhNWI1Mzc4Yjk0ZDU1YzIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ngCAGfJ7pJcZAvvAUXCk0p8Sz4q40fV6m3YdAdvqBvY) ![image](https://private-user-images.githubusercontent.com/106241874/276640575-0caffe11-0a2a-4184-b6a1-45f59f6c24f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzA3MDUsIm5iZiI6MTcwMzQ3MDQwNSwicGF0aCI6Ii8xMDYyNDE4NzQvMjc2NjQwNTc1LTBjYWZmZTExLTBhMmEtNDE4NC1iNmExLTQ1ZjU5ZjZjMjRmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWI4ZjI0MDcxNzFkNmJmMTc4MWU0YTI0OThmZjhjMDYyMzg3ZmEwOTY3OTY1YmQ5ZjU4ZWU0OGJiY2Y5ZTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t1GJgJDjNeYfbjLNq7ecQgeQyf5E_m6iMIvzYR6xUhk)

你这个问题最后怎么解决的

**Comment by xiaoyuebao** [comment]
@Ryaang 看看你的hexo版本，[禁用代码](https://hexo.io/zh-cn/docs/syntax-highlight#%E7%A6%81%E7%94%A8)

禁用
v7.0.0及以下：
```
# _config.yml
highlight:
  enable: false
prismjs:
  enable: false
```
v7.0.0及以上：
```
# _config.yml
syntax_highlighter: # empty
```
