### ISSUE TITLE
git clone之后，这个如何编译呢

### ISSUE THREAD

**Issue by derjeoy** [auroral-ui/hexo-theme-aurora#401]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] (是否与都个问题有有关，请详细描述)

**Describe the solution you'd like**
A clear and concise description of what you want to happen.（描述想要的效果）

**Additional context or screenshots**
Add any other context or screenshots about the feature request here.（附加信息或者截图）

**Comment by bennyxguo** [comment]
详细描述一下你想做的是？

**Comment by derjeoy** [comment]
> 详细描述一下你想做的是？

想魔改  个性化
