### ISSUE TITLE
hexo aurora语言问题

### ISSUE THREAD

**Issue by FailureJack** [auroral-ui/hexo-theme-aurora#410]
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/76461667/1ad871fa-730a-44bb-9910-8fa9df8a4b69)
如上所示，说cn用不了，但是网页能正常显示，有时候不能默认出字，需要手动点一下，请问如何解决这个error

**Comment by bennyxguo** [comment]
之前的版本已经把 `cn` 改用了 `zh-CN`

**Comment by FailureJack** [comment]
> 之前的版本已经把 `cn` 改用了 `zh-CN` 看这里：https://aurora.tridiamond.tech/cn/upgrade/v2.5.html

thanks， thats very helpful
