### ISSUE TITLE
問一下瀏覽次數要怎麼顯示

### ISSUE THREAD

**Issue by dill503084699** [auroral-ui/hexo-theme-aurora#416]
![2023-11-18 16-50-52 的螢幕擷圖](https://github.com/auroral-ui/hexo-theme-aurora/assets/135853235/277cf7d3-1ad4-40c7-af2c-5f60b1b87e75)

**Comment by bennyxguo** [comment]
你要使用 waline 才能用这个功能哦。

**Comment by Ephemeral1y** [comment]
请问用的gitalk插件要怎么增加浏览次数显示呢

**Comment by dill503084699** [comment]
> 你要使用 waline 才能使用這個功能喔。 看這裡：https://aurora.tridiamond.tech/cn/configs/plugins.html#waline

好的我會再試試看的 謝謝大佬

**Comment by bennyxguo** [comment]
> 请问用的gitalk插件要怎么增加浏览次数显示呢

@Ephemeral1y Gitalk 用不了这个，因为它没有这个统计支持。所以只能用卜算子了。
