### ISSUE TITLE
代码高亮可否支持跟右上角的模式按钮同步呢

### ISSUE THREAD

**Issue by twitf** [auroral-ui/hexo-theme-aurora#419]

**Comment by bennyxguo** [comment]
没有明白你的意识，可以展开说说吗？或者给一些截图看看。

**Comment by twitf** [comment]
因为现在的主题里面代码高亮只能设置一种，但是主题有 日间和黑夜2种模式，如果我切换到日间模式，代码主题高亮还是只有一种 就看起来不太协调，所以能不能根据不同的模式 设置不同的高亮，我只是一个想法 具体你看有没有必要实现，辛苦了
