### ISSUE TITLE
shiki：true时，hexo g报错，已参考#390， #398

### ISSUE THREAD

**Issue by cyl-ly** [auroral-ui/hexo-theme-aurora#426]
配置信息截图
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/99932923/54b24a21-a26f-496d-9d9b-c1292dee8e00)

![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/99932923/94e531cd-0f32-42b6-8342-043a867284b8)

![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/99932923/8990f8a9-aefa-4fea-91b0-68f8991e417e)

package
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/99932923/c67dff47-e6fa-497b-957f-d26a29037bb9)
已经参照之前代码高亮的问题，吧hexo版本回退到6.3，并使用作者的dependencies

----
在7.0hexo 版本可以生产，部署，就是不亮 -> 回退到6.3 就开始报错

这个应该从哪开始解决呀，很头痛

**Comment by cyl-ly** [comment]
#390

**Comment by cyl-ly** [comment]
> #390

>#398

**Comment by TikaFlow** [comment]
可以使用[hexo-shiki-plugin](https://github.com/nova1751/hexo-shiki-plugin)这个插件
#367 
#390 
#398
