### ISSUE TITLE
文章显示时间总是以UTC时间为基准，无论date设置成什么

### ISSUE THREAD

**Issue by SoldierRMB** [auroral-ui/hexo-theme-aurora#427]
比如文章Front-Meta中设置成
---
date: 2024-01-01 00:00:00
---
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/75345944/413cb240-e118-49b4-8aa5-4c789e901a09)
文章时间和归档时间会比设置的时间少8个小时
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/75345944/5b08397e-6db5-4310-a9e8-8c6641545b5a)
甚至是2023-01-31😅还能在2023年12月上面出现
![image](https://github.com/auroral-ui/hexo-theme-aurora/assets/75345944/70be9443-af54-468b-8f03-dccc3882fbd7)
在_config.yml中添加timezone: Asia/Shanghai依然无效

**Comment by TikaFlow** [comment]
```yaml
timezone: 'UTC'
```
这样就好了，见[我的博客](https://blog.tika-flow.com/post/%E5%9C%A8%E5%B1%8F%E5%B9%95%E4%B8%8A%E6%98%BE%E7%A4%BA%E6%97%B6%E9%97%B4#hexo%E6%97%B6%E9%97%B4)

**Comment by TikaFlow** [comment]
> ```yaml
> timezone: 'UTC'
> ```
> 
> 这样就好了，见[我的博客](https://blog.tika-flow.com/post/%E5%9C%A8%E5%B1%8F%E5%B9%95%E4%B8%8A%E6%98%BE%E7%A4%BA%E6%97%B6%E9%97%B4#hexo%E6%97%B6%E9%97%B4)

但Aurora主题确实存在时间问题，（按照我上面用UTC时间的话）比如`2023-11-30 16:12:00`这个时间，Aurora会显示`十二月30日`，显然是+8h后导致月份错乱。 @bennyxguo

**Comment by SoldierRMB** [comment]
稍后尝试一下，确实感觉不像是Hexo的bug
