### ISSUE TITLE
【Aurora Docs】使用文档中，配置默认博客语言参数有误

### ISSUE THREAD

**Issue by shmily101** [auroral-ui/hexo-theme-aurora#438]
🔗： [https://aurora.tridiamond.tech/cn/configs/general.html](url)
![ME1712647904005](https://github.com/auroral-ui/hexo-theme-aurora/assets/56313858/dfb4ed87-5729-46b6-bb51-4c8049f25007)

按照文档所述将language配置为cn无法使默认博客语言变为中文，
```
site:
  language: cn
  multi_language: true
```
将language配置为zh-CN可以达到默认中文的效果。

是否为文档未更新

**Comment by shmily101** [comment]
@bennyxguo

**Comment by moziar** [comment]
参考 [升级到 v2.5](https://aurora.tridiamond.tech/cn/upgrade/v2.5.html)
