### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by HarryWangATX** [auroral-ui/hexo-theme-aurora#52]
After updating to Aurora 1.4, the search button doesn't work anymore.

**Comment by HarryWangATX** [comment]
Scrolling breaks after tapping the search button as well.

**Comment by TriDiamond** [comment]
My works fine, try going to my blog website, https://tridiamond.tech, see the problem exist.

**Comment by HarryWangATX** [comment]
https://www.harrycodes.com/
Here is mines, the gittalk seems to be having issues as well

**Comment by TriDiamond** [comment]
> https://www.harrycodes.com/
> Here is mines, the gittalk seems to be having issues as well

Looks like there are something wrong with the CDN.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/24708758/114908935-2bd64600-9e4f-11eb-88ca-40574089accc.png">

Let me try switch to international CDN, see if it's the link's problem.

**Comment by HarryWangATX** [comment]
ok

**Comment by HarryWangATX** [comment]
fixed

**Comment by TriDiamond** [comment]
> ok

@HarryWangATX Update to version 1.4.1, should be all fixed.
