### ISSUE TITLE
MathJax not rendering

### ISSUE THREAD

**Issue by HarryWangATX** [auroral-ui/hexo-theme-aurora#55]
![nomathjax](https://user-images.githubusercontent.com/47877587/114916012-edf30680-9de9-11eb-80d2-c35774455d11.PNG)

doesn't render TeX

**Comment by TriDiamond** [comment]
Go to your hexo root folder than install the hexo majax plugin:

```shell
npm install hexo-filter-mathjax --save
```

**Comment by HarryWangATX** [comment]
seems to still not have rendered.

**Comment by TriDiamond** [comment]
Then use mathjax syntax. I use hexo default plugin to support this, avoiding extra runtime rendering.

**Comment by HarryWangATX** [comment]
fixed!
