### ISSUE TITLE
Tag issue

### ISSUE THREAD

**Issue by HarryWangATX** [auroral-ui/hexo-theme-aurora#59]
The numbers beside the tags are misaligned

**Comment by TriDiamond** [comment]
Please provide a screenshot thanks.

**Comment by HarryWangATX** [comment]
![misadfas](https://user-images.githubusercontent.com/47877587/114979514-9cca2d80-9e50-11eb-8eb8-37a3b851b2a1.PNG)

also happens in the tags componenet on homepage
