### ISSUE TITLE
Post ordering incorrect

### ISSUE THREAD

**Issue by HarryWangATX** [auroral-ui/hexo-theme-aurora#60]
In one of my posts, the previous shows a post that has a later date.

**Comment by TriDiamond** [comment]
Please provide the post's Front-Meta for me to test out this bug.

**Comment by HarryWangATX** [comment]
---
title: Breadth-First Search Algorithm
categories:
  - Traversal
tags:
  - Algorithm
  - BFS
date: 2020-09-16 14:35:07
feature: true
mathjax: true
---

---
title: Hello World
date: 2021-04-15 18:49:36
tags:
  - Test
categories:
  - First Blog
feature: false
mathjax: true
---
