### ISSUE TITLE
修复安卓手机文章页不能显示的bug

### ISSUE THREAD

**Issue by 0wsaddasw0** [auroral-ui/hexo-theme-aurora#73]
遇到的问题:安卓手机浏览器打开文章页，不能正常显示，一直处于加载状态
查找到的原因：Post.vue页有一处代码报错，如下图
![1WHE$57RF~FOB4@B8D37YT](https://user-images.githubusercontent.com/37452224/115948927-b845d000-a503-11eb-919d-2b8bf32d182a.png)
修改建议:经测试，将replaceAll修改为replace后，文章可以能正常显示

**Comment by TriDiamond** [comment]
嗯嗯，这个是 replaceAll 他和浏览器兼容问题。

**Comment by HChange** [comment]
修复的版本多久发布？

**Comment by TriDiamond** [comment]
最快今天我会发布一个版本修复这些问题。
