### ISSUE TITLE
直接访问[/about]页面页面会丢失 

### ISSUE THREAD

**Issue by HChange** [auroral-ui/hexo-theme-aurora#78]
在几位使用该ui插件的网站测试了都存在相同的问题； 
1、https://vn.vic485.xyz/about
2、https://blog.hellochange.cn/about

**Comment by TriDiamond** [comment]
你缺少了了 permalink 的配置。

    步骤 3.1: 打开在 Hexo 根目录下的 _config.yml
    步骤 3.2: 修改 permalink 参数为 /post/:title.html
    
    https://aurora.tridiamond.tech/zh/guide/getting-started.html#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97

**Comment by HChange** [comment]
![image](https://user-images.githubusercontent.com/40381385/117327880-a7af3580-aec5-11eb-8354-f6f3edf45af0.png)
这个真配置了，只是没打包；

**Comment by HChange** [comment]
> 你全体了了permalink的配置。
> 
> ```
> 步骤 3.1: 打开在 Hexo 根目录下的 _config.yml
> 步骤 3.2: 修改 permalink 参数为 /post/:title.html
> 
> https://aurora.tridiamond.tech/zh/guide/getting-started.html#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97
> ```

真配置了。

**Comment by TriDiamond** [comment]
hexo cl & g 重新打包后还是没有用吗？你是用服务器的还是用 github/gitee page？

**Comment by HChange** [comment]
> > > hexo cl & g 重新打包后还是没有用吗？你是用服务器的还是用 github/gitee page？
> > > 没进行打包，直接在服务器跑的项目。
> 
> 这个主题是基于 Hexo 引擎的，需要用 Hexo 生成静态文件哈。如果你是用服务器的话，并且如果你用 Nginx 的话，请在本博客的 nginx 配置中添加这个配置：
> 
> ```
> location / {
>   try_files $uri /index.html;
> }
> ```

现在我 nginx配置是这样的

**Comment by HChange** [comment]
> > > hexo cl & g 重新打包后还是没有用吗？你是用服务器的还是用 github/gitee page？
> > > 没进行打包，直接在服务器跑的项目。
> 
> 这个主题是基于 Hexo 引擎的，需要用 Hexo 生成静态文件哈。如果你是用服务器的话，并且如果你用 Nginx 的话，请在本博客的 nginx 配置中添加这个配置：
> 
> ```
> location / {
>   try_files $uri /index.html;
> }
> ```

代理到 开发服务器 。 其实就是直接跑您这个项目。 /about页面刷新存在404的问题

**Comment by HChange** [comment]
> > > hexo cl & g 重新打包后还是没有用吗？你是用服务器的还是用 github/gitee page？
> > > 没进行打包，直接在服务器跑的项目。
> 
> 这个主题是基于 Hexo 引擎的，需要用 Hexo 生成静态文件哈。如果你是用服务器的话，并且如果你用 Nginx 的话，请在本博客的 nginx 配置中添加这个配置：
> 
> ```
> location / {
>   try_files $uri /index.html;
> }
> ```

😭直接跑你的项目没得问题。结合hexo。莫名其妙就出现这个问题了。也不清楚是哪没配置对。我看了几个部署到托管服务器的blog都有这个问题 。 😣

**Comment by TriDiamond** [comment]
群里好几个小伙伴都是托管服务器的。要不你问问他们吧

**Comment by allinu** [comment]
我也遇到相同的问题了，或者说是更加普遍的问题，每一个页面是可以通过点击，页面跳转访问的，但是一旦刷新就会404，分析页面的URL，感觉应该是路径不全，比如一个博文文件名为`blog.html`，那么它存放的位置为`/post/blog.html`
点击连接会变成`/post/blog`，但是一旦刷新，则会变成直接请求`/post/blog/[index.html]`，找不到，故显示404

**Comment by veyvin** [comment]
@HChange @bennyxguo  about 文件夹生成在了page文件夹下，访问   /page/about

**Comment by psily** [comment]
我在自己的个人服务器上通过hexo 启动也遇到相同问题，解决办法只能手动复制page/about 文件夹到生成静态文件的主目录

**Comment by huangge1199** [comment]
我现在也是这个问题，在首页点过去没问题，单独点新建的页面，“域名/page/新页面“就会404

**Comment by zhongwei-li** [comment]
同样问题，首页点关于可以访问 域名/about，但是直接访问会4040

**Comment by zhongwei-li** [comment]
> 我在自己的个人服务器上通过hexo 启动也遇到相同问题，解决办法只能手动复制page/about 文件夹到生成静态文件的主目录

这种方法 如果用hexo clean，手动复制的东西会被删掉，治标不治本

**Comment by uyloal** [comment]
建议不要使用 hexo server，build 之后使用 nginx 做静态服务。
需要配置一下 nginx，参考 https://router.vuejs.org/zh/guide/essentials/history-mode.html#后端配置例子。
或者寻找一下 hexo server 配置路径重定向的配置。

**Comment by AATIAOTIAOAA** [comment]
我也遇到这个问题，纯粹的github + hexo

**Comment by hachikozjq** [comment]
> 在几位使用该ui插件的网站测试了都存在相同的问题； 1、https://vn.vic485.xyz/about 2、https://blog.hellochange.cn/about

about404你有解决吗？还有话说你的favicon是怎么改的？

**Comment by idnewnil** [comment]
about刷新会404，因为about页面实际上位于`/page/about/index.html`，但在浏览器刷新时会获取`/about`页面，这个页面是不存在的。可以尝试使用HTTP服务器进行重写，如果你用的是Caddy，那么可以加入以下语句。
```
@blog_about {
  host 博客域名
  path /about
}
rewrite @blog_about /page/about/index.html
```

或者说，直接复制或者链接`/page/about/index.html`到`/about`，这个方法我没有试过，不过也是一个思路。

**Comment by IversonTian** [comment]
> > 对于托管，需要设定一些配置
> > ## Netlify
> > 在根目录添加 `netlify.toml` 文件并填入以下内容
> > **netlify.toml**
> > ```toml
> > [[redirects]]
> >   from = "/*"
> >   to = "/index.html"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Vercel
> > 依旧是根目录，添加 `vercel.json`，添加以下内容
> > **vercel.json**
> > ```json
> > {
> >   "version": 2,
> >   "routes": [
> >     { "handle": "filesystem" },
> >     { "src": "/.*", "dest": "/index.html" }
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 参考链接：https://dev.to/alexmercedcoder/deploying-react-angular-svelte-and-vue-to-netlify-vercel-496j
> > @TriDiamond 建议是不是可以在主题配置文件中添加一项是否托管 的配置项，减少此问题出现概率
> 
> 设置了依旧没有作用，用的github.io部署，在放在博客根目录还是主题根目录下？

@uyloal

**Comment by denalon** [comment]
> 在几位使用该ui插件的网站测试了都存在相同的问题； 1、https://vn.vic485.xyz/about 2、https://blog.hellochange.cn/about

about应该在source/about，且about文件夹里放index.md文件

**Comment by BlueWhaleYT** [comment]
我都有這個問題。
```yml
---
title: about
type: about
---
```
加上 `type: about` 就解決了，不知道能不能幫到你。

**Comment by eavnluo01** [comment]
> 我都有這個問題。
> 
> ```yaml
> ---
> title: about
> type: about
> ---
> ```
> 
> 加上 `type: about` 就解決了，不知道能不能幫到你。

厉害了，加上这个就好了😄
