### ISSUE TITLE
Alignment social links in profile section

### ISSUE THREAD

**Issue by wjpvandenheuvel** [auroral-ui/hexo-theme-aurora#80]
Custom social links (font awesome) are aligned to the right in the profile section. Centering the icons would be a nicer fit.

![image](https://user-images.githubusercontent.com/416365/117062329-9e866300-ad23-11eb-8553-2e8460deebf3.png)

**Comment by TriDiamond** [comment]
I couldn't reproduce this, can you post your config for this part, also which version are you using? @wjpvandenheuvel
