### ISSUE TITLE
Add links of friends.

### ISSUE THREAD

**Issue by bennyxguo** [auroral-ui/hexo-theme-aurora#96]

**Comment by pplmx** [comment]
FYI.
https://github.com/SukkaW/Friends

**Comment by TriDiamond** [comment]
> FYI.
> https://github.com/SukkaW/Friends

哇，好的，我这个版本就在给主题做友链功能，等我实现好了，我就会去建一个 PR 互相交换。谢谢你的提议呀～
Waaa, okay, I am working on this feature for the theme, when I finished this feature I will go fill in a PR, thanks for the suggestion!
