### ISSUE TITLE
关于站点设置及logo反馈

### ISSUE THREAD

**Issue by o1f** [auroral-ui/hexo-theme-aurora#99]
![image](https://user-images.githubusercontent.com/28326356/118278982-2e36c900-b4fd-11eb-9b80-2086c57134a2.png)
站点设置建议统一一下, 为站点名称 ,浏览器状态栏显示站点,而头部却是作者名称
站点设置建议使用hexo _config.yml 的配置信息.

至于主题的站点配置,直接设置为首页作者信息,
![image](https://user-images.githubusercontent.com/28326356/118279335-98e80480-b4fd-11eb-8f36-0620e47866a1.png)

现在的配置站点配置和作者配置 相互交叠 , 建议分开配置.站点可以使用hexo 配置 , 首页作者介绍使用主题配置

logo项配置无法正常加载,且优先级在文字类后,需要删除作者项才显示,且无法正常加载
![image](https://user-images.githubusercontent.com/28326356/118279958-4e1abc80-b4fe-11eb-8d68-16eff0d496b3.png)

**Comment by zhongwei-li** [comment]
同样问题，望解决
